"""

The Glass - Column Registry

Single source of truth for database column definitions and provider source
mappings.  Column names match the actual PostgreSQL schema exactly.

Each column entry carries a ``sources`` attribute using this shape:

    dataset_mapping[league_key][source_key][entity] -> source definition

Columns with no external source (system columns) have ``dataset_mapping: None``.

The synthetic identity column ``the_glass_id`` and per-source identity
columns (e.g. ``nba_api_id``) are emitted directly by the DDL generator
(see src/core/lib/ddl.py); they are intentionally not represented here.
"""

from typing import Dict, List, TypedDict, Union


class DatasetMapping(TypedDict):
    dataset: str
    column: str
    transform: Union[str, None]

class ColumnDef(TypedDict):
    type: str
    scope: Union[str, List[str]]
    nullable: bool
    default: Union[str, int, None]
    entity_types: Union[List[str], None]
    update_frequency: Union[str, None]
    managed_by: str
    domain: Union[str, None]
    comment: Union[str, None]
    dataset_mapping: Union[Dict[str, Dict[str, Dict[str, DatasetMapping]]], None]

DB_COLUMNS: Dict[str, ColumnDef] = {

    # ------------------------------------------------------------------
    # SYSTEM COLUMNS  (managed by DB / ETL engine, no provider sources)
    # Note: 'id' (SERIAL PK) is auto-generated by DDL, not defined here
    # ------------------------------------------------------------------
    'entity_type': {
        'type': 'VARCHAR(10)',
        'scope': ['runs', 'tasks', 'backfill'],
        'nullable': True,
        'default': None,
        'entity_types': None,
        'update_frequency': 'per_execution',
        'managed_by': 'execution_context',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'updated_at': {
        'type': 'TIMESTAMP',
        'scope': ['profiles', 'stats', 'rosters'],
        'nullable': False,
        'default': 'CURRENT_TIMESTAMP',
        'entity_types': ['league', 'player', 'team'],
        'update_frequency': 'per_execution',
        'managed_by': 'db',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'created_at': {
        'type': 'TIMESTAMP',
        'scope': ['profiles', 'stats', 'rosters'],
        'nullable': True,
        'default': 'CURRENT_TIMESTAMP',
        'entity_types': ['league', 'player', 'team'],
        'update_frequency': None,
        'managed_by': 'db',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'season': {
        'type': 'VARCHAR(7)',
        'scope': ['profiles', 'stats', 'runs', 'rosters', 'backfill'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'managed_by': 'execution_context',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'season_type': {
        'type': 'VARCHAR(3)',
        'scope': ['profiles', 'stats', 'backfill'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'managed_by': 'execution_context',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'notes': {
        'type': 'TEXT',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'the_glass_sheets': {
                    'player': {'dataset': 'players', 'field': 'Notes'},
                    'team': {'dataset': 'teams', 'field': 'Notes'},
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # ENTITY INFORMATION  (league / team / player profile data)
    # ------------------------------------------------------------------
    'team_id': {
        'type': 'BIGINT',
        'scope': ['stats'],
        'nullable': False,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'TEAM_ID',
                    },
                },
            },
        },
    },
    'player_id': {
        'type': 'BIGINT',
        'scope': ['stats'],
        'nullable': False,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'managed_by': 'execution_context',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'name': {
        'type': 'VARCHAR(100)',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['league', 'player', 'team'],
        'update_frequency': 'annual',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'PLAYER_NAME',
                        'transform': 'safe_str',
                    },
                    'team': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'TEAM_NAME',
                        'transform': 'safe_str',
                    },
                },
            },
        },
    },
    'height_ins_no_shoes': {
        'type': 'SMALLINT',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'draftcombineplayeranthro',
                        'field': 'HEIGHT_WO_SHOES',
                        'transform': 'parse_height',
                    },
                },
            },
        },
    },
    'height_ins_with_shoes': {
        'type': 'SMALLINT',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'draftcombineplayeranthro',
                        'field': 'HEIGHT_W_SHOES',
                        'transform': 'parse_height',
                    },
                },
                'the_glass_sheets': {
                    'player': {'dataset': 'players', 'field': 'Height'},
                },
            },
        },
    },
    'weight_lbs': {
        'type': 'SMALLINT',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'commonallplayers', 'field': 'WEIGHT'},
                },
                'the_glass_sheets': {
                    'player': {'dataset': 'players', 'field': 'Weight'},
                },
            },
        },
    },
    'wingspan_ins': {
        'type': 'SMALLINT',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'draftcombineplayeranthro',
                        'field': 'WINGSPAN',
                        'transform': 'parse_height',
                    },
                },
                'the_glass_sheets': {
                    'player': {'dataset': 'players', 'field': 'Wingspan'},
                },
            },
        },
    },
    'handedness': {
        'type': 'CHAR',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'the_glass_sheets': {
                    'player': {'dataset': 'players', 'field': 'Handedness'},
                },
            },
        },
    },
    'birthdate': {
        'type': 'DATE',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'commonallplayers',
                        'field': 'BIRTHDATE',
                        'transform': 'parse_birthdate',
                    },
                },
            },
        },
    },
    'seasons_exp': {
        'type': 'SMALLINT',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'commonallplayers', 'field': 'SEASON_EXP'},
                },
            },
        },
    },
    'abbr': {
        'type': 'VARCHAR(5)',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['league', 'team'],
        'update_frequency': 'annual',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'team': {'dataset': 'team_metadata', 'field': 'TEAM_ABBREVIATION', 'transform': 'safe_str'},
                },
            },
        },
    },
    'conf': {
        'type': 'VARCHAR(50)',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['team'],
        'update_frequency': 'annual',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'team': {'dataset': 'team_metadata', 'field': 'TEAM_CONFERENCE', 'transform': 'safe_str'},
                },
            },
        },
    },
    'gender': {
        'type': 'CHAR',
        'scope': ['profiles'],
        'nullable': True,
        'default': None,
        'entity_types': ['league', 'team', 'player'],
        'update_frequency': None,
        'managed_by': 'execution_context',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    # ------------------------------------------------------------------
    # GAMES & MINUTES
    # ------------------------------------------------------------------
    'games': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': False,
        'default': 0,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'GP'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'GP'},
                },
            },
        },
    },
    'minutes_x10': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': False,
        'default': 0,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'MIN', 'scale': 10},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'MIN', 'scale': 10},
                },
            },
        },
    },
    'wins': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'W'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'W'},
                },
            },
        },
    },
    'tracking_games': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': False,
        'default': 0,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'GP',
                        'params': {'pt_measure_type': 'SpeedDistance', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'GP',
                        'params': {'pt_measure_type': 'SpeedDistance', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    'tracking_minutes_x10': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': False,
        'default': 0,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'MIN',
                        'scale': 10,
                        'params': {'pt_measure_type': 'SpeedDistance', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'MIN',
                        'scale': 10,
                        'params': {'pt_measure_type': 'SpeedDistance', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    'hustle_games': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': False,
        'default': 0,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguehustlestatsplayer', 'field': 'G'},
                    'team': {'dataset': 'leaguehustlestatsteam', 'field': 'G'},
                },
            },
        },
    },
    'hustle_minutes_x10': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': False,
        'default': 0,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguehustlestatsplayer', 'field': 'MIN', 'scale': 10},
                    'team': {'dataset': 'leaguehustlestatsteam', 'field': 'MIN', 'scale': 10},
                },
            },
        },
    },
    'off_games': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': False,
        'default': 0,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'teamplayeronoffsummary',
                        'tier': 'team_call',
                        'result_set': 'PlayersOffCourtTeamPlayerOnOffSummary',
                        'player_id_field': 'VS_PLAYER_ID',
                        'field': 'GP',
                        'aggregation': 'sum',
                    },
                },
            },
        },
    },
    'off_minutes_x10': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': False,
        'default': 0,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'teamplayeronoffsummary',
                        'tier': 'team_call',
                        'result_set': 'PlayersOffCourtTeamPlayerOnOffSummary',
                        'player_id_field': 'VS_PLAYER_ID',
                        'field': 'MIN',
                        'scale': 10,
                        'aggregation': 'sum',
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # SCORING: 2-POINT
    # ------------------------------------------------------------------
    'fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'FGM',
                        'derived': {'subtract': 'FG3M'},
                    },
                    'team': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'FGM',
                        'derived': {'subtract': 'FG3M'},
                    },
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_FGM',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                        'derived': {'subtract': 'OPP_FG3M'},
                    },
                },
            },
        },
    },
    'fg2a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'FGA',
                        'derived': {'subtract': 'FG3A'},
                    },
                    'team': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'FGA',
                        'derived': {'subtract': 'FG3A'},
                    },
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_FGA',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                        'derived': {'subtract': 'OPP_FG3A'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # SCORING: 3-POINT
    # ------------------------------------------------------------------
    'fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'FG3M'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'FG3M'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_FG3M',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    'fg3a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'FG3A'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'FG3A'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_FG3A',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # SCORING: FREE THROWS
    # ------------------------------------------------------------------
    'ftm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'FTM'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'FTM'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_FTM',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    'fta': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'FTA'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'FTA'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_FTA',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # SHOT TRACKING: CONTESTED / OPEN  x  RIM / ALL
    # ------------------------------------------------------------------
    'cont_rim_fgm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FGM',
                        'multi_call': [
                            {
                                'close_def_dist_range_nullable': '0-2 Feet - Very Tight',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                            {
                                'close_def_dist_range_nullable': '2-4 Feet - Tight',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FGM',
                        'multi_call': [
                            {
                                'close_def_dist_range_nullable': '0-2 Feet - Very Tight',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                            {
                                'close_def_dist_range_nullable': '2-4 Feet - Tight',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'cont_rim_fga': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FGA',
                        'multi_call': [
                            {
                                'close_def_dist_range_nullable': '0-2 Feet - Very Tight',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                            {
                                'close_def_dist_range_nullable': '2-4 Feet - Tight',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FGA',
                        'multi_call': [
                            {
                                'close_def_dist_range_nullable': '0-2 Feet - Very Tight',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                            {
                                'close_def_dist_range_nullable': '2-4 Feet - Tight',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'open_rim_fgm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FGM',
                        'multi_call': [
                            {
                                'close_def_dist_range_nullable': '4-6 Feet - Open',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                            {
                                'close_def_dist_range_nullable': '6+ Feet - Wide Open',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FGM',
                        'multi_call': [
                            {
                                'close_def_dist_range_nullable': '4-6 Feet - Open',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                            {
                                'close_def_dist_range_nullable': '6+ Feet - Wide Open',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'open_rim_fga': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FGA',
                        'multi_call': [
                            {
                                'close_def_dist_range_nullable': '4-6 Feet - Open',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                            {
                                'close_def_dist_range_nullable': '6+ Feet - Wide Open',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FGA',
                        'multi_call': [
                            {
                                'close_def_dist_range_nullable': '4-6 Feet - Open',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                            {
                                'close_def_dist_range_nullable': '6+ Feet - Wide Open',
                                'general_range_nullable': 'Less Than 10 ft',
                            },
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'cont_fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FG2M',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '0-2 Feet - Very Tight'},
                            {'close_def_dist_range_nullable': '2-4 Feet - Tight'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FG2M',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '0-2 Feet - Very Tight'},
                            {'close_def_dist_range_nullable': '2-4 Feet - Tight'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'cont_fg2a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FG2A',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '0-2 Feet - Very Tight'},
                            {'close_def_dist_range_nullable': '2-4 Feet - Tight'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FG2A',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '0-2 Feet - Very Tight'},
                            {'close_def_dist_range_nullable': '2-4 Feet - Tight'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'open_fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FG2M',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '4-6 Feet - Open'},
                            {'close_def_dist_range_nullable': '6+ Feet - Wide Open'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FG2M',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '4-6 Feet - Open'},
                            {'close_def_dist_range_nullable': '6+ Feet - Wide Open'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'open_fg2a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FG2A',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '4-6 Feet - Open'},
                            {'close_def_dist_range_nullable': '6+ Feet - Wide Open'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FG2A',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '4-6 Feet - Open'},
                            {'close_def_dist_range_nullable': '6+ Feet - Wide Open'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'cont_fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FG3M',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '0-2 Feet - Very Tight'},
                            {'close_def_dist_range_nullable': '2-4 Feet - Tight'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FG3M',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '0-2 Feet - Very Tight'},
                            {'close_def_dist_range_nullable': '2-4 Feet - Tight'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'cont_fg3a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FG3A',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '0-2 Feet - Very Tight'},
                            {'close_def_dist_range_nullable': '2-4 Feet - Tight'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FG3A',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '0-2 Feet - Very Tight'},
                            {'close_def_dist_range_nullable': '2-4 Feet - Tight'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'open_fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FG3M',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '4-6 Feet - Open'},
                            {'close_def_dist_range_nullable': '6+ Feet - Wide Open'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FG3M',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '4-6 Feet - Open'},
                            {'close_def_dist_range_nullable': '6+ Feet - Wide Open'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    'open_fg3a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerptshot',
                        'field': 'FG3A',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '4-6 Feet - Open'},
                            {'close_def_dist_range_nullable': '6+ Feet - Wide Open'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                    'team': {
                        'dataset': 'leaguedashteamptshot',
                        'field': 'FG3A',
                        'multi_call': [
                            {'close_def_dist_range_nullable': '4-6 Feet - Open'},
                            {'close_def_dist_range_nullable': '6+ Feet - Wide Open'},
                        ],
                        'result_set': 'LeagueDashPTShots',
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # PUTBACKS & DUNKS  (pipeline: filter shooting splits -> aggregate)
    # ------------------------------------------------------------------
    'putbacks': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'playerdashboardbyshootingsplits',
                        'tier': 'player',
                        'params': {'measure_type_detailed': 'Base', 'per_mode_detailed': 'Totals'},
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'ShotTypePlayerDashboard',
                                'field': 'FGM',
                                'filter_field': 'GROUP_VALUE',
                                'filter_values': ['Putback Dunk Shot', 'Putback Layup Shot', 'Tip Dunk Shot', 'Tip Layup Shot'],
                            },
                            {'type': 'aggregate', 'method': 'sum'},
                        ],
                    },
                    'team': {
                        'dataset': 'teamdashboardbyshootingsplits',
                        'tier': 'team',
                        'params': {
                            'measure_type_detailed_defense': 'Base',
                            'per_mode_detailed': 'Totals',
                        },
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'ShotTypeTeamDashboard',
                                'field': 'FGM',
                                'filter_field': 'GROUP_VALUE',
                                'filter_values': ['Putback Dunk Shot', 'Putback Layup Shot', 'Tip Dunk Shot', 'Tip Layup Shot'],
                            },
                            {'type': 'aggregate', 'method': 'sum'},
                        ],
                    },
                },
            },
        },
    },
    'dunks': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'playerdashboardbyshootingsplits',
                        'tier': 'player',
                        'params': {'measure_type_detailed': 'Base', 'per_mode_detailed': 'Totals'},
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'ShotTypePlayerDashboard',
                                'field': 'FGM',
                                'filter_field': 'GROUP_VALUE',
                                'filter_values': [
                                    'Alley Oop Dunk Shot',
                                    'Cutting Dunk Shot',
                                    'Driving Dunk Shot',
                                    'Driving Reverse Dunk Shot',
                                    'Dunk Shot',
                                    'Putback Dunk Shot',
                                    'Reverse Dunk Shot',
                                    'Running Alley Oop Dunk Shot',
                                    'Running Dunk Shot',
                                    'Tip Dunk Shot',
                                ],
                            },
                            {'type': 'aggregate', 'method': 'sum'},
                        ],
                    },
                    'team': {
                        'dataset': 'teamdashboardbyshootingsplits',
                        'tier': 'team',
                        'params': {
                            'measure_type_detailed_defense': 'Base',
                            'per_mode_detailed': 'Totals',
                        },
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'ShotTypeTeamDashboard',
                                'field': 'FGM',
                                'filter_field': 'GROUP_VALUE',
                                'filter_values': [
                                    'Alley Oop Dunk Shot',
                                    'Cutting Dunk Shot',
                                    'Driving Dunk Shot',
                                    'Driving Reverse Dunk Shot',
                                    'Dunk Shot',
                                    'Putback Dunk Shot',
                                    'Reverse Dunk Shot',
                                    'Running Alley Oop Dunk Shot',
                                    'Running Dunk Shot',
                                    'Tip Dunk Shot',
                                ],
                            },
                            {'type': 'aggregate', 'method': 'sum'},
                        ],
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # UNASSISTED FIELD GOALS  (per-player shooting splits)
    # ------------------------------------------------------------------
    'unassisted_rim_fgm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'playerdashboardbyshootingsplits',
                        'tier': 'player',
                        'params': {'measure_type_detailed': 'Base', 'per_mode_detailed': 'Totals'},
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'AssistTracking',
                                'field': 'FGM',
                                'filter_field': 'SHOT_TYPE',
                                'filter_values': ['AtRim'],
                            },
                        ],
                    },
                },
            },
        },
    },
    'unassisted_fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'playerdashboardbyshootingsplits',
                        'tier': 'player',
                        'params': {'measure_type_detailed': 'Base', 'per_mode_detailed': 'Totals'},
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'AssistTracking',
                                'field': 'FGM',
                                'filter_field': 'SHOT_TYPE',
                                'filter_values': ['2PT'],
                            },
                        ],
                    },
                },
            },
        },
    },
    'unassisted_fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'playerdashboardbyshootingsplits',
                        'tier': 'player',
                        'params': {'measure_type_detailed': 'Base', 'per_mode_detailed': 'Totals'},
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'AssistTracking',
                                'field': 'FGM',
                                'filter_field': 'SHOT_TYPE',
                                'filter_values': ['3PT'],
                            },
                        ],
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # REBOUNDS
    # ------------------------------------------------------------------
    'o_rebs': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'OREB'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'OREB'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_OREB',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    'd_rebs': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'DREB'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'DREB'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_DREB',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    'o_reb_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'OREB_PCT',
                        'scale': 1000,
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                    'team': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OREB_PCT',
                        'scale': 1000,
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                },
            },
        },
    },
    'd_reb_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'DREB_PCT',
                        'scale': 1000,
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                    'team': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'DREB_PCT',
                        'scale': 1000,
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                },
            },
        },
    },
    'cont_o_rebs': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'playerdashptreb',
                        'tier': 'player',
                        'params': {'team_id': 0},
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'OverallRebounding',
                                'field': 'C_OREB',
                            },
                        ],
                    },
                    'team': {
                        'dataset': 'teamdashptreb',
                        'tier': 'team',
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'OverallRebounding',
                                'field': 'C_OREB',
                            },
                        ],
                    },
                },
            },
        },
    },
    'cont_d_rebs': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'playerdashptreb',
                        'tier': 'player',
                        'params': {'team_id': 0},
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'OverallRebounding',
                                'field': 'C_DREB',
                            },
                        ],
                    },
                    'team': {
                        'dataset': 'teamdashptreb',
                        'tier': 'team',
                        'operations': [
                            {
                                'type': 'extract',
                                'result_set': 'OverallRebounding',
                                'field': 'C_DREB',
                            },
                        ],
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # PLAYMAKING
    # ------------------------------------------------------------------
    'assists': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'AST'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'AST'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_AST',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    'pot_assists': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'POTENTIAL_AST',
                        'params': {'pt_measure_type': 'Passing', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'POTENTIAL_AST',
                        'params': {'pt_measure_type': 'Passing', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    'passes': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'PASSES_MADE',
                        'params': {'pt_measure_type': 'Passing', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'PASSES_MADE',
                        'params': {'pt_measure_type': 'Passing', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    'sec_assists': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'SECONDARY_AST',
                        'params': {'pt_measure_type': 'Passing', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'SECONDARY_AST',
                        'params': {'pt_measure_type': 'Passing', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # BALL HANDLING
    # ------------------------------------------------------------------
    'touches': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'TOUCHES',
                        'params': {'pt_measure_type': 'Possessions', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'TOUCHES',
                        'params': {'pt_measure_type': 'Possessions', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    'time_on_ball': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'TIME_OF_POSS',
                        'params': {'pt_measure_type': 'Possessions', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'TIME_OF_POSS',
                        'params': {'pt_measure_type': 'Possessions', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    'possessions': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'POSS',
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                    'team': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'POSS',
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # TURNOVERS
    # ------------------------------------------------------------------
    'turnovers': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'TOV'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'TOV'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_TOV',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # DISTANCE
    # ------------------------------------------------------------------
    'o_dist_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'DIST_MILES_OFF',
                        'scale': 10,
                        'params': {'pt_measure_type': 'SpeedDistance', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'DIST_MILES_OFF',
                        'scale': 10,
                        'params': {'pt_measure_type': 'SpeedDistance', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    'd_dist_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptstats',
                        'field': 'DIST_MILES_DEF',
                        'scale': 10,
                        'params': {'pt_measure_type': 'SpeedDistance', 'player_or_team': 'Player'},
                    },
                    'team': {
                        'dataset': 'leaguedashptstats',
                        'field': 'DIST_MILES_DEF',
                        'scale': 10,
                        'params': {'pt_measure_type': 'SpeedDistance', 'player_or_team': 'Team'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # DEFENSE: STEALS / BLOCKS / FOULS
    # ------------------------------------------------------------------
    'steals': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'STL'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'STL'}
                },
            },
        },
    },
    'blocks': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'BLK'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'BLK'},
                },
            },
        },
    },
    'fouls': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguedashplayerstats', 'field': 'PF'},
                    'team': {'dataset': 'leaguedashteamstats', 'field': 'PF'},
                    'opponent': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OPP_PF',
                        'params': {'measure_type_detailed_defense': 'Opponent'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # HUSTLE STATS
    # ------------------------------------------------------------------
    'deflections': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'hustle',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguehustlestatsplayer', 'field': 'DEFLECTIONS'},
                    'team': {'dataset': 'leaguehustlestatsteam', 'field': 'DEFLECTIONS'},
                },
            },
        },
    },
    'charges_drawn': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'hustle',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguehustlestatsplayer', 'field': 'CHARGES_DRAWN'},
                    'team': {'dataset': 'leaguehustlestatsteam', 'field': 'CHARGES_DRAWN'},
                },
            },
        },
    },
    'contests': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'hustle',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {'dataset': 'leaguehustlestatsplayer', 'field': 'CONTESTED_SHOTS'},
                    'team': {'dataset': 'leaguehustlestatsteam', 'field': 'CONTESTED_SHOTS'},
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # DEFENSIVE SHOT TRACKING  (leaguedashptdefend / leaguedashptteamdefend)
    # ------------------------------------------------------------------
    'd_rim_fgm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'FGM',
                        'params': {'defense_category': 'Less Than 10Ft'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'FGM',
                        'params': {'defense_category': 'Less Than 10Ft'},
                    },
                },
            },
        },
    },
    'd_rim_fga': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'FGA_LT_10',
                        'params': {'defense_category': 'Less Than 10Ft'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'FGA_LT_10',
                        'params': {'defense_category': 'Less Than 10Ft'},
                    },
                },
            },
        },
    },
    'd_fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'FG2M',
                        'params': {'defense_category': '2 Pointers'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'FG2M',
                        'params': {'defense_category': '2 Pointers'},
                    },
                },
            },
        },
    },
    'd_fg2a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'FG2A',
                        'params': {'defense_category': '2 Pointers'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'FG2A',
                        'params': {'defense_category': '2 Pointers'},
                    },
                },
            },
        },
    },
    'd_fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'FG3M',
                        'params': {'defense_category': '3 Pointers'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'FG3M',
                        'params': {'defense_category': '3 Pointers'},
                    },
                },
            },
        },
    },
    'd_fg3a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'FG3A',
                        'params': {'defense_category': '3 Pointers'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'FG3A',
                        'params': {'defense_category': '3 Pointers'},
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # RATINGS
    # ------------------------------------------------------------------
    'o_rtg_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'OFF_RATING',
                        'scale': 10,
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                    'team': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'OFF_RATING',
                        'scale': 10,
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                },
            },
        },
    },
    'd_rtg_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashplayerstats',
                        'field': 'DEF_RATING',
                        'scale': 10,
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                    'team': {
                        'dataset': 'leaguedashteamstats',
                        'field': 'DEF_RATING',
                        'scale': 10,
                        'params': {'measure_type_detailed_defense': 'Advanced'},
                    },
                },
            },
        },
    },
    'off_o_rtg_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': 'onoff',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'teamplayeronoffsummary',
                        'tier': 'team_call',
                        'result_set': 'PlayersOffCourtTeamPlayerOnOffSummary',
                        'player_id_field': 'VS_PLAYER_ID',
                        'field': 'OFF_RATING',
                        'scale': 10,
                        'aggregation': 'minute_weighted',
                    },
                },
            },
        },
    },
    'off_d_rtg_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'domain': 'onoff',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'teamplayeronoffsummary',
                        'tier': 'team_call',
                        'result_set': 'PlayersOffCourtTeamPlayerOnOffSummary',
                        'player_id_field': 'VS_PLAYER_ID',
                        'field': 'DEF_RATING',
                        'scale': 10,
                        'aggregation': 'minute_weighted',
                    },
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # DEFENSIVE REAL FG% DIFFERENTIALS
    # ------------------------------------------------------------------
    'real_d_fg_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'PCT_PLUSMINUS',
                        'scale': 1000,
                        'params': {'defense_category': 'Overall'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'PCT_PLUSMINUS',
                        'scale': 1000,
                        'params': {'defense_category': 'Overall'},
                    },
                },
            },
        },
    },
    'real_d_rim_fg_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'PLUSMINUS',
                        'scale': 1000,
                        'params': {'defense_category': 'Less Than 10Ft'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'PLUSMINUS',
                        'scale': 1000,
                        'params': {'defense_category': 'Less Than 10Ft'},
                    },
                },
            },
        },
    },
    'real_d_fg2_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'PLUSMINUS',
                        'scale': 1000,
                        'params': {'defense_category': '2 Pointers'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'PLUSMINUS',
                        'scale': 1000,
                        'params': {'defense_category': '2 Pointers'},
                    },
                },
            },
        },
    },
    'real_d_fg3_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'per_execution',
        'domain': 'tracking',
        'comment': None,
        'dataset_mapping': {
            'nba': {
                'nba_api': {
                    'player': {
                        'dataset': 'leaguedashptdefend',
                        'field': 'PLUSMINUS',
                        'scale': 1000,
                        'params': {'defense_category': '3 Pointers'},
                    },
                    'team': {
                        'dataset': 'leaguedashptteamdefend',
                        'field': 'PLUSMINUS',
                        'scale': 1000,
                        'params': {'defense_category': '3 Pointers'},
                    },
                },
            },
        },
    },

    # ------------------------------------------------------------------
    # OPERATIONAL COLUMNS - RUNS TABLE
    # ------------------------------------------------------------------
    'pipeline': {
        'type': 'VARCHAR(10)',
        'scope': ['runs', 'tasks'],
        'nullable': False,
        'default': None,
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'status': {
        'type': 'VARCHAR(20)',
        'scope': ['runs', 'tasks'],
        'nullable': False,
        'default': "'pending'",
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'started_at': {
        'type': 'TIMESTAMP',
        'scope': ['runs', 'tasks'],
        'nullable': False,
        'default': 'NOW()',
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'completed_at': {
        'type': 'TIMESTAMP',
        'scope': ['runs', 'tasks', 'backfill'],
        'nullable': True,
        'default': None,
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'total_items': {
        'type': 'INTEGER',
        'scope': ['runs'],
        'nullable': True,
        'default': '0',
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'completed_items': {
        'type': 'INTEGER',
        'scope': ['runs'],
        'nullable': True,
        'default': '0',
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'total_rows': {
        'type': 'INTEGER',
        'scope': ['runs'],
        'nullable': True,
        'default': '0',
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'error_message': {
        'type': 'TEXT',
        'scope': ['runs', 'tasks'],
        'nullable': True,
        'default': None,
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },

    # ------------------------------------------------------------------
    # OPERATIONAL COLUMNS - TASKS TABLE
    # ------------------------------------------------------------------
    'run_id': {
        'type': 'INTEGER',
        'scope': ['tasks'],
        'nullable': False,
        'default': None,
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'item_key': {
        'type': 'TEXT',
        'scope': ['tasks'],
        'nullable': False,
        'default': None,
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'rows_written': {
        'type': 'INTEGER',
        'scope': ['tasks'],
        'nullable': True,
        'default': '0',
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'retry_count': {
        'type': 'INTEGER',
        'scope': ['tasks'],
        'nullable': True,
        'default': '0',
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'source_key': {
        'type': 'VARCHAR(50)',
        'scope': ['backfill'],
        'nullable': False,
        'default': None,
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'coverage_signature': {
        'type': 'TEXT',
        'scope': ['backfill'],
        'nullable': False,
        'default': None,
        'entity_types': None,
        'update_frequency': 'per_execution',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },

    # ------------------------------------------------------------------
    # ROSTER COLUMNS (league_rosters, team_rosters)
    # Shared operational/data columns only.  FK columns (league_id, team_id,
    # player_id) are derived directly from ROSTER_TABLES.foreign_keys by
    # the DDL generator, so they do not belong here.
    # ------------------------------------------------------------------
    'is_active': {
        'type': 'BOOLEAN',
        'scope': ['rosters'],
        'nullable': False,
        'default': 'TRUE',
        'entity_types': ['team', 'player'],
        'update_frequency': 'per_execution',
        'managed_by': 'execution_context',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
    'jersey_num': {
        'type': 'VARCHAR(3)',
        'scope': ['rosters'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'per_execution',
        'managed_by': 'source',
        'domain': None,
        'comment': None,
        'dataset_mapping': None,
    },
}
