"""
The Glass - Publish Column Registry

Tab column definitions (TAB_COLUMNS) and the field-derivation logic that
maps display columns back to database column references.
"""

from typing import Any, Dict

from src.publish.lib.formulas import (
    calculate_age,
    lookup,
    seasons_in_query,
    team_average,
)

# ============================================================================
# COLUMN DEFINITIONS
# ============================================================================

# Valid attribute value sets (co-located with the schema they constrain)
_VALID_SECTIONS = {
    'entities', 'profile', 'evaluation',
    'current_stats', 'historical_stats', 'postseason_stats', 'identity',
}
_VALID_SUBSECTIONS = {
    'rates', 'scoring', 'ball_management', 'rebounding',
    'distance', 'defense', 'opponent', 'team_ratings', 'nba',
    'League', 'Player',
}
_VALID_TABS = {'all_teams', 'all_players', 'individual_team'}
_VALID_STATS_MODES = {'basic', 'advanced', 'both'}
_VALID_LINKS = {'team_link', None}
_VALID_FORMATS = {'text', 'number', 'percentage', 'measurement'}
_VALID_WIDTH_CLASSES = {
    'auto', 'measurement', 'four_char', 'four_char_dec',
    'three_char_dec', 'two_char', 'two_char_dec'
}
_VALID_WIDTH_CLASS_TYPES = (str, int)
_VALID_LEAGUES = {'nba', 'ncaa'}

_VALID_ALIGNS = {'left', 'center'}
_VALID_EMPHASIS = {'bold', None}

TAB_COLUMNS: Dict[str, Any] = {
    'players': {
        'description': 'PlayerName',
        'sections': ['entities'],
        'subsection': None,
        'tabs': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'auto',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'left',
        'emphasis': 'bold',
        'font_size': 10,
        'inputs': {
            'player': {'fields': ('name',)},
            'team': {'fields': ()},
            'opponents': {'fields': ()},
        },
        'values': {
            'player': lambda row, ctx: row.get('name'),
            'team': lambda row, ctx: 'TEAM',
            'opponents': lambda row, ctx: 'OPPONENTS'
        }
    },
    'teams': {
        'description': 'Team Name',
        'sections': ['entities'],
        'subsection': None,
        'tabs': ['all_teams'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'auto',
        'link': 'team_link',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'left',
        'emphasis': 'bold',
        'font_size': 10,
        'inputs': {
            'all_teams': {'fields': ('name',)},
        },
        'values': {
            'all_teams': lambda row, ctx: row.get('name')
        }
    },
    'team': {
        'description': 'Team Abbreviation',
        'sections': ['profile'],
        'subsection': 'League',
        'tabs': ['all_players'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'four_char',
        'link': 'team_link',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('team_id',), 'source': 'teams'},
        },
        'values': {
            'player': lambda row, ctx: lookup(row.get('team_id'), 'teams', 'abbr', ctx)
        }
    },
    'conf': {
        'description': 'Conference',
        'sections': ['profile'],
        'subsection': 'League',
        'tabs': ['all_teams'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'four_char',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'all_teams': {'fields': ('conf',)},
        },
        'values': {
            'all_teams': lambda row, ctx: row.get('conf')
        }
    },
    'J#': {
        'description': 'Jersey Number',
        'sections': ['profile'],
        'subsection': 'League',
        'tabs': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'two_char',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': (), 'source': 'team_rosters'},
        },
        'values': {
            'player': lambda row, ctx: row.get('jersey_num')
        }
    },
    'exp': {
        'description': 'Seasons with Playing Experience',
        'sections': ['profile'],
        'subsection': 'League',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'two_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'average',
        'default': '0',
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('seasons_exp',)},
            'team': {'fields': ('seasons_exp',), 'source': 'players'},
            'all_teams': {'fields': ('seasons_exp',), 'source': 'players'},
        },
        'values': {
            'player': lambda row, ctx: row.get('seasons_exp'),
            'team': lambda row, ctx: team_average(lambda p, c: p.get('seasons_exp'), ctx),
            'all_teams': lambda row, ctx: team_average(lambda p, c: p.get('seasons_exp'), ctx)
        }
    },
    'age': {
        'description': 'Age',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('birthdate',)},
            'team': {'fields': ('birthdate',), 'source': 'players'},
            'all_teams': {'fields': ('birthdate',), 'source': 'players'},
        },
        'values': {
            'player': lambda row, ctx: calculate_age(row.get('birthdate')),
            'team': lambda row, ctx: team_average(lambda p, c: calculate_age(p.get('birthdate')), ctx),
            'all_teams': lambda row, ctx: team_average(lambda p, c: calculate_age(p.get('birthdate')), ctx)
        },
    },
    'ht': {
        'description': 'Height in Feet\'Inches"',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'measurement',
        'decimal_places': 1,
        'width_class': 'measurement',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('height_ins_with_shoes',)},
            'team': {'fields': ('height_ins_with_shoes',), 'source': 'players'},
            'all_teams': {'fields': ('height_ins_with_shoes',), 'source': 'players'},
        },
        'values': {
            'player': lambda row, ctx: row.get('height_ins_with_shoes'),
            'team': lambda row, ctx: team_average(lambda p, c: p.get('height_ins_with_shoes'), ctx),
            'all_teams': lambda row, ctx: team_average(lambda p, c: p.get('height_ins_with_shoes'), ctx)
        }
    },
    'wt': {
        'description': 'Weight in Pounds',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('weight_lbs',)},
            'team': {'fields': ('weight_lbs',), 'source': 'players'},
            'all_teams': {'fields': ('weight_lbs',), 'source': 'players'},
        },
        'values': {
            'player': lambda row, ctx: row.get('weight_lbs'),
            'team': lambda row, ctx: team_average(lambda p, c: p.get('weight_lbs'), ctx),
            'all_teams': lambda row, ctx: team_average(lambda p, c: p.get('weight_lbs'), ctx)
        }
    },
    'ws': {
        'description': 'Wingspan in Feet\'Inches" (Editable)',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': ['player'],
        'rate_domain': None,
        'format': 'measurement',
        'decimal_places': 1,
        'width_class': 'measurement',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('wingspan_ins',)},
            'team': {'fields': ('wingspan_ins',), 'source': 'players'},
            'all_teams': {'fields': ('wingspan_ins',), 'source': 'players'},
        },
        'values': {
            'player': lambda row, ctx: row.get('wingspan_ins'),
            'team': lambda row, ctx: team_average(lambda p, c: p.get('wingspan_ins'), ctx),
            'all_teams': lambda row, ctx: team_average(lambda p, c: p.get('wingspan_ins'), ctx)
        }
    },
    '🖐️': {
        'description': 'Handedness (Editable)',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': ['player'],
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'two_char',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('hand',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('hand')
        }
    },
    'notes': {
        'description': 'Personal thoughts, observations, findings, etc (Editable)',
        'sections': ['evaluation'],
        'subsection': None,
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': ['player', 'individual_team', 'all_teams'],
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 500,
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'editable',
        'default': None,
        'align': 'left',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('notes',)},
            'team': {'fields': ('notes',)},
            'all_teams': {'fields': ('notes',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('notes'),
            'team': lambda row, ctx: row.get('notes'),
            'all_teams': lambda row, ctx: row.get('notes')
        }
    },
    'szn': {
        'description': 'Seasons Played',
        'sections': ['historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ()},
            'team': {'fields': ()},
            'all_teams': {'fields': ()},
        },
        'values': {
            'player': lambda row, ctx: seasons_in_query(ctx),
            'team': lambda row, ctx: seasons_in_query(ctx),
            'all_teams': lambda row, ctx: seasons_in_query(ctx)
        }
    },
    'gms': {
        'description': 'Games Played per Season',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('games',)},
            'team': {'fields': ('games',)},
            'all_teams': {'fields': ('games',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('games') / seasons_in_query(ctx) if row.get('games') is not None else None,
            'team': lambda row, ctx: row.get('games') / seasons_in_query(ctx) if row.get('games') is not None else None,
            'all_teams': lambda row, ctx: row.get('games') / seasons_in_query(ctx) if row.get('games') is not None else None
        },
    },
    'min': {
        'description': 'Minutes Played per Game',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'team_value',
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('minutes_x10', 'games')},
            'team': {'fields': ('minutes_x10', 'games')},
            'all_teams': {'fields': ('minutes_x10', 'games')},
        },
        'values': {
            'player': lambda row, ctx: (row.get('minutes_x10') / 10) / row.get('games') if row.get('minutes_x10') is not None and row.get('games') else None,
            'team': lambda row, ctx: (row.get('minutes_x10') / 10) / row.get('games') if row.get('minutes_x10') is not None and row.get('games') else None,
            'all_teams': lambda row, ctx: (row.get('minutes_x10') / 10) / row.get('games') if row.get('minutes_x10') is not None and row.get('games') else None
        }
    },
    'pace': {
        'description': 'Possessions per 40 Mins',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('possessions', 'minutes_x10')},
            'team': {'fields': ('possessions', 'minutes_x10')},
            'all_teams': {'fields': ('possessions', 'minutes_x10')},
        },
        'values': {
            'player': lambda row, ctx: (row.get('possessions') * 40) / (row.get('minutes_x10') / 10) if row.get('possessions') is not None and row.get('minutes_x10') else None,
            'team': lambda row, ctx: (row.get('possessions') * 40) / (row.get('minutes_x10') / 10) if row.get('possessions') is not None and row.get('minutes_x10') else None,
            'all_teams': lambda row, ctx: (row.get('possessions') * 40) / (row.get('minutes_x10') / 10) if row.get('possessions') is not None and row.get('minutes_x10') else None
        }
    },
    'pts': {
        'description': 'Points',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fg2m', 'fg3m', 'ftm')},
            'team': {'fields': ('fg2m', 'fg3m', 'ftm')},
            'all_teams': {'fields': ('fg2m', 'fg3m', 'ftm')},
            'opponents': {'fields': ('opp_fg2m', 'opp_fg3m', 'opp_ftm')},
        },
        'values': {
            'player': lambda row, ctx: (row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm'],
            'team': lambda row, ctx: (row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm'],
            'all_teams': lambda row, ctx: (row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm'],
            'opponents': lambda row, ctx: (row['opp_fg2m'] * 2) + (row['opp_fg3m'] * 3) + row['opp_ftm']
        }
    },
    'p/ta': {
        'description': 'Points per "True" FGA (FGA + FTA per FT Trip Estimation) or TS% * 2',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fg2m', 'fg3m', 'ftm', 'fg2a', 'fg3a', 'fta')},
            'team': {'fields': ('fg2m', 'fg3m', 'ftm', 'fg2a', 'fg3a', 'fta')},
            'all_teams': {'fields': ('fg2m', 'fg3m', 'ftm', 'fg2a', 'fg3a', 'fta')},
            'opponents': {'fields': ('opp_fg2m', 'opp_fg3m', 'opp_ftm', 'opp_fg2a', 'opp_fg3a', 'opp_fta')},
        },
        'values': {
            'player': lambda row, ctx: ((row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)),
            'team': lambda row, ctx: ((row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)),
            'all_teams': lambda row, ctx: ((row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)),
            'opponents': lambda row, ctx: ((row['opp_fg2m'] * 2) + (row['opp_fg3m'] * 3) + row['opp_ftm']) / (row['opp_fg2a'] + row['opp_fg3a'] + (row['opp_fta'] * 0.44))
        }
    },
    '2a': {
        'description': 'Two-Point FGA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fg2a',)},
            'team': {'fields': ('fg2a',)},
            'all_teams': {'fields': ('fg2a',)},
            'opponents': {'fields': ('opp_fg2a',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('fg2a'),
            'team': lambda row, ctx: row.get('fg2a'),
            'all_teams': lambda row, ctx: row.get('fg2a'),
            'opponents': lambda row, ctx: row.get('opp_fg2a')
        }
    },
    'p/2': {
        'description': 'Points per 2A',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fg2m', 'fg2a')},
            'team': {'fields': ('fg2m', 'fg2a')},
            'all_teams': {'fields': ('fg2m', 'fg2a')},
            'opponents': {'fields': ('opp_fg2m', 'opp_fg2a')},
        },
        'values': {
            'player': lambda row, ctx: 2 * (row.get('fg2m') / row.get('fg2a')) if row.get('fg2m') is not None and row.get('fg2a') else None,
            'team': lambda row, ctx: 2 * (row.get('fg2m') / row.get('fg2a')) if row.get('fg2m') is not None and row.get('fg2a') else None,
            'all_teams': lambda row, ctx: 2 * (row.get('fg2m') / row.get('fg2a')) if row.get('fg2m') is not None and row.get('fg2a') else None,
            'opponents': lambda row, ctx: 2 * (row.get('opp_fg2m') / row.get('opp_fg2a')) if row.get('opp_fg2m') is not None and row.get('opp_fg2a') else None
        }
    },
    'ora': {
        'description': 'Open 2A at the Rim (Closest Defender Beyond 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('open_rim_fga',)},
            'team': {'fields': ('open_rim_fga',)},
            'all_teams': {'fields': ('open_rim_fga',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('open_rim_fga'),
            'team': lambda row, ctx: row.get('open_rim_fga'),
            'all_teams': lambda row, ctx: row.get('open_rim_fga')
        }
    },
    'p/or': {
        'description': 'Points per Open 2A at the Rim (Closest Defender Beyond 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('open_rim_fgm', 'open_rim_fga')},
            'team': {'fields': ('open_rim_fgm', 'open_rim_fga')},
            'all_teams': {'fields': ('open_rim_fgm', 'open_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: 2 * (row.get('open_rim_fgm') / row.get('open_rim_fga')) if row.get('open_rim_fgm') is not None and row.get('open_rim_fga') else None,
            'team': lambda row, ctx: 2 * (row.get('open_rim_fgm') / row.get('open_rim_fga')) if row.get('open_rim_fgm') is not None and row.get('open_rim_fga') else None,
            'all_teams': lambda row, ctx: 2 * (row.get('open_rim_fgm') / row.get('open_rim_fga')) if row.get('open_rim_fgm') is not None and row.get('open_rim_fga') else None
        }
    },
    'cra': {
        'description': 'Contested 2A at the Rim (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_rim_fga',)},
            'team': {'fields': ('cont_rim_fga',)},
            'all_teams': {'fields': ('cont_rim_fga',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('cont_rim_fga'),
            'team': lambda row, ctx: row.get('cont_rim_fga'),
            'all_teams': lambda row, ctx: row.get('cont_rim_fga')
        }
    },
    'p/cr': {
        'description': 'Points per Contested 2A at the Rim (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_rim_fgm', 'cont_rim_fga')},
            'team': {'fields': ('cont_rim_fgm', 'cont_rim_fga')},
            'all_teams': {'fields': ('cont_rim_fgm', 'cont_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: 2 * (row.get('cont_rim_fgm') / row.get('cont_rim_fga')) if row.get('cont_rim_fgm') is not None and row.get('cont_rim_fga') else None,
            'team': lambda row, ctx: 2 * (row.get('cont_rim_fgm') / row.get('cont_rim_fga')) if row.get('cont_rim_fgm') is not None and row.get('cont_rim_fga') else None,
            'all_teams': lambda row, ctx: 2 * (row.get('cont_rim_fgm') / row.get('cont_rim_fga')) if row.get('cont_rim_fgm') is not None and row.get('cont_rim_fga') else None
        }
    },
    'uar': {
        'description': 'Unassisted 2A Made at the Rim (Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('unassisted_rim_fgm',)},
            'team': {'fields': ('unassisted_rim_fgm',)},
            'all_teams': {'fields': ('unassisted_rim_fgm',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('unassisted_rim_fgm'),
            'team': lambda row, ctx: row.get('unassisted_rim_fgm'),
            'all_teams': lambda row, ctx: row.get('unassisted_rim_fgm')
        }
    },
    'oma': {
        'description': 'Open 2A in the Mid-Range (Closest Defender Beyond 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_fg2a', 'cont_rim_fga')},
            'team': {'fields': ('cont_fg2a', 'cont_rim_fga')},
            'all_teams': {'fields': ('cont_fg2a', 'cont_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: row.get('cont_fg2a') - row.get('cont_rim_fga') if row.get('cont_fg2a') is not None and row.get('cont_rim_fga') is not None else None,
            'team': lambda row, ctx: row.get('cont_fg2a') - row.get('cont_rim_fga') if row.get('cont_fg2a') is not None and row.get('cont_rim_fga') is not None else None,
            'all_teams': lambda row, ctx: row.get('cont_fg2a') - row.get('cont_rim_fga') if row.get('cont_fg2a') is not None and row.get('cont_rim_fga') is not None else None
        }
    },
    'p/om': {
        'description': 'Points per Open 2A in the Mid-Range (Closest Defender Beyond 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('open_fg2m', 'open_rim_fgm', 'open_fg2a', 'open_rim_fga')},
            'team': {'fields': ('open_fg2m', 'open_rim_fgm', 'open_fg2a', 'open_rim_fga')},
            'all_teams': {'fields': ('open_fg2m', 'open_rim_fgm', 'open_fg2a', 'open_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: 2 * ((row['open_fg2m'] - row['open_rim_fgm']) / (row['open_fg2a'] - row['open_rim_fga'])),
            'team': lambda row, ctx: 2 * ((row['open_fg2m'] - row['open_rim_fgm']) / (row['open_fg2a'] - row['open_rim_fga'])),
            'all_teams': lambda row, ctx: 2 * ((row['open_fg2m'] - row['open_rim_fgm']) / (row['open_fg2a'] - row['open_rim_fga']))
        }
    },
    'cma': {
        'description': 'Contested 2A in the Mid-Range (Closest Defender Within 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_fg2a', 'cont_rim_fga')},
            'team': {'fields': ('cont_fg2a', 'cont_rim_fga')},
            'all_teams': {'fields': ('cont_fg2a', 'cont_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: row.get('cont_fg2a') - row.get('cont_rim_fga') if row.get('cont_fg2a') is not None and row.get('cont_rim_fga') is not None else None,
            'team': lambda row, ctx: row.get('cont_fg2a') - row.get('cont_rim_fga') if row.get('cont_fg2a') is not None and row.get('cont_rim_fga') is not None else None,
            'all_teams': lambda row, ctx: row.get('cont_fg2a') - row.get('cont_rim_fga') if row.get('cont_fg2a') is not None and row.get('cont_rim_fga') is not None else None
        }
    },
    'p/cm': {
        'description': 'Points per Contested 2A in the Mid-Range (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_fg2m', 'cont_rim_fgm', 'cont_fg2a', 'cont_rim_fga')},
            'team': {'fields': ('cont_fg2m', 'cont_rim_fgm', 'cont_fg2a', 'cont_rim_fga')},
            'all_teams': {'fields': ('cont_fg2m', 'cont_rim_fgm', 'cont_fg2a', 'cont_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: 2 * ((row['cont_fg2m'] - row['cont_rim_fgm']) / (row['cont_fg2a'] - row['cont_rim_fga'])),
            'team': lambda row, ctx: 2 * ((row['cont_fg2m'] - row['cont_rim_fgm']) / (row['cont_fg2a'] - row['cont_rim_fga'])),
            'all_teams': lambda row, ctx: 2 * ((row['cont_fg2m'] - row['cont_rim_fgm']) / (row['cont_fg2a'] - row['cont_rim_fga']))
        }
    },
    'uam': {
        'description': 'Unassisted 2A Made in the Mid-Range (Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('unassisted_fg2m', 'unassisted_rim_fgm')},
            'team': {'fields': ('unassisted_fg2m', 'unassisted_rim_fgm')},
            'all_teams': {'fields': ('unassisted_fgm', 'unassisted_rim_fgm')},
        },
        'values': {
            'player': lambda row, ctx: row.get('unassisted_fg2m') - row.get('unassisted_rim_fgm') if row.get('unassisted_fg2m') is not None and row.get('unassisted_rim_fgm') is not None else None,
            'team': lambda row, ctx: row.get('unassisted_fg2m') - row.get('unassisted_rim_fgm') if row.get('unassisted_fg2m') is not None and row.get('unassisted_rim_fgm') is not None else None,
            'all_teams': lambda row, ctx: row.get('unassisted_fgm') - row.get('unassisted_rim_fgm') if row.get('unassisted_fgm') is not None and row.get('unassisted_rim_fgm') is not None else None
        }
    },
    '3a': {
        'description': 'Three-Point FGA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fg3a',)},
            'team': {'fields': ('fg3a',)},
            'all_teams': {'fields': ('fg3a',)},
            'opponents': {'fields': ('opp_fg3a',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('fg3a'),
            'team': lambda row, ctx: row.get('fg3a'),
            'all_teams': lambda row, ctx: row.get('fg3a'),
            'opponents': lambda row, ctx: row.get('opp_fg3a')
        }
    },
    'p/3': {
        'description': 'Points per 3A',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fg3m', 'fg3a')},
            'team': {'fields': ('fg3m', 'fg3a')},
            'all_teams': {'fields': ('fg3m', 'fg3a')},
            'opponents': {'fields': ('opp_fg3m', 'opp_fg3a')},
        },
        'values': {
            'player': lambda row, ctx: 3 * (row.get('fg3m') / row.get('fg3a')) if row.get('fg3m') is not None and row.get('fg3a') else None,
            'team': lambda row, ctx: 3 * (row.get('fg3m') / row.get('fg3a')) if row.get('fg3m') is not None and row.get('fg3a') else None,
            'all_teams': lambda row, ctx: 3 * (row.get('fg3m') / row.get('fg3a')) if row.get('fg3m') is not None and row.get('fg3a') else None,
            'opponents': lambda row, ctx: 3 * (row.get('opp_fg3m') / row.get('opp_fg3a')) if row.get('opp_fg3m') is not None and row.get('opp_fg3a') else None
        }
    },
    'o3a': {
        'description': 'Open 3A (Closest Defender Beyond 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('open_fg3a',)},
            'team': {'fields': ('open_fg3a',)},
            'all_teams': {'fields': ('open_fg3a',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('open_fg3a'),
            'team': lambda row, ctx: row.get('open_fg3a'),
            'all_teams': lambda row, ctx: row.get('open_fg3a')
        }
    },
    'p/o3': {
        'description': 'Points per Open 3A (Closest Defender Beyond 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('open_fg3m', 'open_fg3a')},
            'team': {'fields': ('open_fg3m', 'open_fg3a')},
            'all_teams': {'fields': ('open_fg3m', 'open_fg3a')},
        },
        'values': {
            'player': lambda row, ctx: 3 * (row.get('open_fg3m') / row.get('open_fg3a')) if row.get('open_fg3m') is not None and row.get('open_fg3a') else None,
            'team': lambda row, ctx: 3 * (row.get('open_fg3m') / row.get('open_fg3a')) if row.get('open_fg3m') is not None and row.get('open_fg3a') else None,
            'all_teams': lambda row, ctx: 3 * (row.get('open_fg3m') / row.get('open_fg3a')) if row.get('open_fg3m') is not None and row.get('open_fg3a') else None
        }
    },
    'c3a': {
        'description': 'Contested 3A (Closest Defender Within 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_fg3a',)},
            'team': {'fields': ('cont_fg3a',)},
            'all_teams': {'fields': ('cont_fg3a',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('cont_fg3a'),
            'team': lambda row, ctx: row.get('cont_fg3a'),
            'all_teams': lambda row, ctx: row.get('cont_fg3a')
        }
    },
    'p/c3': {
        'description': 'Points per Contested 3A (Closest Defender Within 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_fg3m', 'cont_fg3a')},
            'team': {'fields': ('cont_fg3m', 'cont_fg3a')},
            'all_teams': {'fields': ('cont_fg3m', 'cont_fg3a')},
        },
        'values': {
            'player': lambda row, ctx: 3 * (row.get('cont_fg3m') / row.get('cont_fg3a')) if row.get('cont_fg3m') is not None and row.get('cont_fg3a') else None,
            'team': lambda row, ctx: 3 * (row.get('cont_fg3m') / row.get('cont_fg3a')) if row.get('cont_fg3m') is not None and row.get('cont_fg3a') else None,
            'all_teams': lambda row, ctx: 3 * (row.get('cont_fg3m') / row.get('cont_fg3a')) if row.get('cont_fg3m') is not None and row.get('cont_fg3a') else None
        }
    },
    'ua3': {
        'description': 'Unassisted 3A Made',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('unassisted_fg3m',)},
            'team': {'fields': ('unassisted_fg3m',)},
            'all_teams': {'fields': ('unassisted_fg3m',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('unassisted_fg3m'),
            'team': lambda row, ctx: row.get('unassisted_fg3m'),
            'all_teams': lambda row, ctx: row.get('unassisted_fg3m')
        }
    },
    'tftr': {
        'description': '"True" Free throw Rate (FT Trip Estimation / (FGA + FT Trip Estimation))',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fta', 'fg2a', 'fg3a')},
            'team': {'fields': ('fta', 'fg2a', 'fg3a')},
            'all_teams': {'fields': ('fta', 'fg2a', 'fg3a')},
            'opponents': {'fields': ('opp_fta', 'opp_fg2a', 'opp_fg3a')},
        },
        'values': {
            'player': lambda row, ctx: (row['fta'] * 0.44) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)),
            'team': lambda row, ctx: (row['fta'] * 0.44) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)),
            'all_teams': lambda row, ctx: (row['fta'] * 0.44) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)),
            'opponents': lambda row, ctx: (row['opp_fta'] * 0.44) / (row['opp_fg2a'] + row['opp_fg3a'] + (row['opp_fta'] * 0.44))
        }
    },
    'p/ft': {
        'description': 'Points per FTA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('ftm', 'fta')},
            'team': {'fields': ('ftm', 'fta')},
            'all_teams': {'fields': ('ftm', 'fta')},
            'opponents': {'fields': ('opp_ftm', 'opp_fta')},
        },
        'values': {
            'player': lambda row, ctx: row.get('ftm') / row.get('fta') if row.get('ftm') is not None and row.get('fta') else None,
            'team': lambda row, ctx: row.get('ftm') / row.get('fta') if row.get('ftm') is not None and row.get('fta') else None,
            'all_teams': lambda row, ctx: row.get('ftm') / row.get('fta') if row.get('ftm') is not None and row.get('fta') else None,
            'opponents': lambda row, ctx: row.get('opp_ftm') / row.get('opp_fta') if row.get('opp_ftm') is not None and row.get('opp_fta') else None
        }
    },
    'dnk': {
        'description': 'Dunks',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('dunks',)},
            'team': {'fields': ('dunks',)},
            'all_teams': {'fields': ('dunks',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('dunks'),
            'team': lambda row, ctx: row.get('dunks'),
            'all_teams': lambda row, ctx: row.get('dunks')
        }
    },
    'tou': {
        'description': 'Instances of Holding the Ball',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('touches',)},
            'team': {'fields': ('touches',)},
            'all_teams': {'fields': ('touches',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('touches'),
            'team': lambda row, ctx: row.get('touches'),
            'all_teams': lambda row, ctx: row.get('touches')
        }
    },
    'spt': {
        'description': 'Seconds per Touch',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'two_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('time_on_ball', 'touches')},
            'team': {'fields': ('time_on_ball', 'touches')},
            'all_teams': {'fields': ('time_on_ball', 'touches')},
        },
        'values': {
            'player': lambda row, ctx: (60 * row.get('time_on_ball')) / row.get('touches') if row.get('time_on_ball') is not None and row.get('touches') else None,
            'team': lambda row, ctx: (60 * row.get('time_on_ball')) / row.get('touches') if row.get('time_on_ball') is not None and row.get('touches') else None,
            'all_teams': lambda row, ctx: (60 * row.get('time_on_ball')) / row.get('touches') if row.get('time_on_ball') is not None and row.get('touches') else None
        }
    },
    '%trs': {
        'description': 'Percentage of Touches Resulting in a Shot',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fg2a', 'fg3a', 'fta', 'touches')},
            'team': {'fields': ('fg2a', 'fg3a', 'fta', 'touches')},
            'all_teams': {'fields': ('fg2a', 'fg3a', 'fta', 'touches')},
        },
        'values': {
            'player': lambda row, ctx: (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)) / row['touches'],
            'team': lambda row, ctx: (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)) / row['touches'],
            'all_teams': lambda row, ctx: (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)) / row['touches']
        }
    },
    '%trp': {
        'description': 'Percentage of Touches Resulting in a Pass',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('passes', 'touches')},
            'team': {'fields': ('passes', 'touches')},
            'all_teams': {'fields': ('passes', 'touches')},
        },
        'values': {
            'player': lambda row, ctx: row.get('passes') / row.get('touches') if row.get('passes') is not None and row.get('touches') else None,
            'team': lambda row, ctx: row.get('passes') / row.get('touches') if row.get('passes') is not None and row.get('touches') else None,
            'all_teams': lambda row, ctx: row.get('passes') / row.get('touches') if row.get('passes') is not None and row.get('touches') else None
        }
    },
    '%trt': {
        'description': 'Percentage of Touches Resulting in a Turnover',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('turnovers', 'touches')},
            'team': {'fields': ('turnovers', 'touches')},
            'all_teams': {'fields': ('turnovers', 'touches')},
        },
        'values': {
            'player': lambda row, ctx: row.get('turnovers') / row.get('touches') if row.get('turnovers') is not None and row.get('touches') else None,
            'team': lambda row, ctx: row.get('turnovers') / row.get('touches') if row.get('turnovers') is not None and row.get('touches') else None,
            'all_teams': lambda row, ctx: row.get('turnovers') / row.get('touches') if row.get('turnovers') is not None and row.get('touches') else None
        }
    },
    'ast': {
        'description': 'Assists',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('assists',)},
            'team': {'fields': ('assists',)},
            'all_teams': {'fields': ('assists',)},
            'opponents': {'fields': ('opp_assists',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('assists'),
            'team': lambda row, ctx: row.get('assists'),
            'all_teams': lambda row, ctx: row.get('assists'),
            'opponents': lambda row, ctx: row.get('opp_assists')
        }
    },
    'past': {
        'description': 'Potential Assists (Passes that lead to a FGA)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'sec_assists',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('pot_assists',)},
            'team': {'fields': ('pot_assists',)},
            'all_teams': {'fields': ('pot_assists',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('pot_assists'),
            'team': lambda row, ctx: row.get('pot_assists'),
            'all_teams': lambda row, ctx: row.get('pot_assists')
        }
    },
    '2ast': {
        'description': 'Secondary Assists (Passes that Lead to an Assist)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'sec_assists',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('sec_assists',)},
            'team': {'fields': ('sec_assists',)},
            'all_teams': {'fields': ('sec_assists',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('sec_assists'),
            'team': lambda row, ctx: row.get('sec_assists'),
            'all_teams': lambda row, ctx: row.get('sec_assists')
        }
    },
    'tov': {
        'description': 'Turnovers',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('turnovers',)},
            'team': {'fields': ('turnovers',)},
            'all_teams': {'fields': ('turnovers',)},
            'opponents': {'fields': ('opp_turnovers',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('turnovers'),
            'team': lambda row, ctx: row.get('turnovers'),
            'all_teams': lambda row, ctx: row.get('turnovers'),
            'opponents': lambda row, ctx: row.get('opp_turnovers')
        }
    },
    'or%': {
        'description': 'Offensive Rebound Percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('o_reb_pct_x1000',)},
            'team': {'fields': ('o_reb_pct_x1000',)},
            'all_teams': {'fields': ('o_reb_pct_x1000',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('o_reb_pct_x1000') / 1000 if row.get('o_reb_pct_x1000') is not None else None,
            'team': lambda row, ctx: row.get('o_reb_pct_x1000') / 1000 if row.get('o_reb_pct_x1000') is not None else None,
            'all_teams': lambda row, ctx: row.get('o_reb_pct_x1000') / 1000 if row.get('o_reb_pct_x1000') is not None else None
        }
    },
    'cor%': {
        'description': 'Contested Offensive Rebound Percentage (Percentage of Offensive Rebounds that are Contested)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_o_rebs', 'o_rebs')},
            'team': {'fields': ('cont_o_rebs', 'o_rebs')},
            'all_teams': {'fields': ('cont_o_rebs', 'o_rebs')},
        },
        'values': {
            'player': lambda row, ctx: row.get('cont_o_rebs') / row.get('o_rebs') if row.get('cont_o_rebs') is not None and row.get('o_rebs') else None,
            'team': lambda row, ctx: row.get('cont_o_rebs') / row.get('o_rebs') if row.get('cont_o_rebs') is not None and row.get('o_rebs') else None,
            'all_teams': lambda row, ctx: row.get('cont_o_rebs') / row.get('o_rebs') if row.get('cont_o_rebs') is not None and row.get('o_rebs') else None
        }
    },
    'dr%': {
        'description': 'Defensive Rebound Percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_reb_pct_x1000',)},
            'team': {'fields': ('d_reb_pct_x1000',)},
            'all_teams': {'fields': ('d_reb_pct_x1000',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('d_reb_pct_x1000') / 1000 if row.get('d_reb_pct_x1000') is not None else None,
            'team': lambda row, ctx: row.get('d_reb_pct_x1000') / 1000 if row.get('d_reb_pct_x1000') is not None else None,
            'all_teams': lambda row, ctx: row.get('d_reb_pct_x1000') / 10 if row.get('d_reb_pct_x1000') is not None else None
        }
    },
    'cdr%': {
        'description': 'Contested Defensive Rebound Percentage (Percentage of Defensive Rebounds that are Contested)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('cont_d_rebs', 'd_rebs')},
            'team': {'fields': ('cont_d_rebs', 'd_rebs')},
            'all_teams': {'fields': ('cont_d_rebs', 'd_rebs')},
        },
        'values': {
            'player': lambda row, ctx: row.get('cont_d_rebs') / row.get('d_rebs') if row.get('cont_d_rebs') is not None and row.get('d_rebs') else None,
            'team': lambda row, ctx: row.get('cont_d_rebs') / row.get('d_rebs') if row.get('cont_d_rebs') is not None and row.get('d_rebs') else None,
            'all_teams': lambda row, ctx: row.get('cont_d_rebs') / row.get('d_rebs') if row.get('cont_d_rebs') is not None and row.get('d_rebs') else None
        }
    },
    'pbs': {
        'description': 'Putbacks (FGM immediately following an offensive rebound)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('putbacks',)},
            'team': {'fields': ('putbacks',)},
            'all_teams': {'fields': ('putbacks',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('putbacks'),
            'team': lambda row, ctx: row.get('putbacks'),
            'all_teams': lambda row, ctx: row.get('putbacks')
        }
    },
    'odst': {
        'description': 'Offensive Distance Traveled in Miles',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distance',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('o_dist_x10',)},
            'team': {'fields': ('o_dist_x10',)},
            'all_teams': {'fields': ('o_dist_x10',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('o_dist_x10') / 10 if row.get('o_dist_x10') is not None else None,
            'team': lambda row, ctx: row.get('o_dist_x10') / 10 if row.get('o_dist_x10') is not None else None,
            'all_teams': lambda row, ctx: row.get('o_dist_x10') / 10 if row.get('o_dist_x10') is not None else None
        }
    },
    'ddst': {
        'description': 'Defensive Distance Traveled in Miles',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distance',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_dist_x10',)},
            'team': {'fields': ('d_dist_x10',)},
            'all_teams': {'fields': ('d_dist_x10',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('d_dist_x10') / 10 if row.get('d_dist_x10') is not None else None,
            'team': lambda row, ctx: row.get('d_dist_x10') / 10 if row.get('d_dist_x10') is not None else None,
            'all_teams': lambda row, ctx: row.get('d_dist_x10') / 10 if row.get('d_dist_x10') is not None else None
        }
    },
    'dra': {
        'description': 'Defended 2A at the Rim (Closest Defender for FGA Within 5 Feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_rim_fga',)},
            'team': {'fields': ('d_rim_fga',)},
            'all_teams': {'fields': ('d_rim_fga',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('d_rim_fga'),
            'team': lambda row, ctx: row.get('d_rim_fga'),
            'all_teams': lambda row, ctx: row.get('d_rim_fga')
        }
    },
    'p/dr': {
        'description': 'Points Allowed per Defended FGA at the Rim (Closest Defender for FGA Within 5 Feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_rim_fgm', 'd_rim_fga')},
            'team': {'fields': ('d_rim_fgm', 'd_rim_fga')},
            'all_teams': {'fields': ('d_rim_fgm', 'd_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: 2 * (row.get('d_rim_fgm') / row.get('d_rim_fga')) if row.get('d_rim_fgm') is not None and row.get('d_rim_fga') else None,
            'team': lambda row, ctx: 2 * (row.get('d_rim_fgm') / row.get('d_rim_fga')) if row.get('d_rim_fgm') is not None and row.get('d_rim_fga') else None,
            'all_teams': lambda row, ctx: 2 * (row.get('d_rim_fgm') / row.get('d_rim_fga')) if row.get('d_rim_fgm') is not None and row.get('d_rim_fga') else None
        }
    },
    'dma': {
        'description': 'Defended 2A in the Mid-Range (Closest Defender for FGA Beyond 5 Feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_fg2a', 'd_rim_fga')},
            'team': {'fields': ('d_fg2a', 'd_rim_fga')},
            'all_teams': {'fields': ('d_fg2a', 'd_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: row.get('d_fg2a') - row.get('d_rim_fga') if row.get('d_fg2a') is not None and row.get('d_rim_fga') is not None else None,
            'team': lambda row, ctx: row.get('d_fg2a') - row.get('d_rim_fga') if row.get('d_fg2a') is not None and row.get('d_rim_fga') is not None else None,
            'all_teams': lambda row, ctx: row.get('d_fg2a') - row.get('d_rim_fga') if row.get('d_fg2a') is not None and row.get('d_rim_fga') is not None else None
        }
    },
    'p/dm': {
        'description': 'Points Allowed per Defended FGA in the Mid-Range (Closest Defender for FGA Beyond 5 Feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_fg2m', 'd_rim_fgm', 'd_fg2a', 'd_rim_fga')},
            'team': {'fields': ('d_fg2m', 'd_rim_fgm', 'd_fg2a', 'd_rim_fga')},
            'all_teams': {'fields': ('d_fg2m', 'd_rim_fgm', 'd_fg2a', 'd_rim_fga')},
        },
        'values': {
            'player': lambda row, ctx: 2 * ((row['d_fg2m'] - row['d_rim_fgm']) / (row['d_fg2a'] - row['d_rim_fga'])),
            'team': lambda row, ctx: 2 * ((row['d_fg2m'] - row['d_rim_fgm']) / (row['d_fg2a'] - row['d_rim_fga'])),
            'all_teams': lambda row, ctx: 2 * ((row['d_fg2m'] - row['d_rim_fgm']) / (row['d_fg2a'] - row['d_rim_fga']))
        }
    },
    'd3a': {
        'description': 'Defended 3A (Closest Defender)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_fg3a',)},
            'team': {'fields': ('d_fg3a',)},
            'all_teams': {'fields': ('d_fg3a',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('d_fg3a'),
            'team': lambda row, ctx: row.get('d_fg3a'),
            'all_teams': lambda row, ctx: row.get('d_fg3a')
        }
    },
    'p/d3': {
        'description': 'Points Allowed per Defended 3A (Closest Defender)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_fg3m', 'd_fg3a')},
            'team': {'fields': ('d_fg3m', 'd_fg3a')},
            'all_teams': {'fields': ('d_fg3m', 'd_fg3a')},
        },
        'values': {
            'player': lambda row, ctx: 3 * (row.get('d_fg3m') / row.get('d_fg3a')) if row.get('d_fg3m') is not None and row.get('d_fg3a') else None,
            'team': lambda row, ctx: 3 * (row.get('d_fg3m') / row.get('d_fg3a')) if row.get('d_fg3m') is not None and row.get('d_fg3a') else None,
            'all_teams': lambda row, ctx: 3 * (row.get('d_fg3m') / row.get('d_fg3a')) if row.get('d_fg3m') is not None and row.get('d_fg3a') else None
        }
    },
    'cont': {
        'description': 'Defensive Shot Contests',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'hustle',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('contests',)},
            'team': {'fields': ('contests',)},
            'all_teams': {'fields': ('contests',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('contests'),
            'team': lambda row, ctx: row.get('contests'),
            'all_teams': lambda row, ctx: row.get('contests')
        }
    },
    'blk': {
        'description': 'Blocks',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('blocks',)},
            'team': {'fields': ('blocks',)},
            'all_teams': {'fields': ('blocks',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('blocks'),
            'team': lambda row, ctx: row.get('blocks'),
            'all_teams': lambda row, ctx: row.get('blocks')
        }
    },
    'defl': {
        'description': 'Deflections of the ball on Defense',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'hustle',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('deflections',)},
            'team': {'fields': ('deflections',)},
            'all_teams': {'fields': ('deflections',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('deflections'),
            'team': lambda row, ctx: row.get('deflections'),
            'all_teams': lambda row, ctx: row.get('deflections')
        }
    },
    'stl': {
        'description': 'Steals',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('steals',)},
            'team': {'fields': ('steals',)},
            'all_teams': {'fields': ('steals',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('steals'),
            'team': lambda row, ctx: row.get('steals'),
            'all_teams': lambda row, ctx: row.get('steals')
        }
    },
    'st+c': {
        'description': 'Steals + Charges Drawn',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('steals', 'charges_drawn')},
            'team': {'fields': ('steals', 'charges_drawn')},
            'all_teams': {'fields': ('steals', 'charges_drawn')},
        },
        'values': {
            'player': lambda row, ctx: row.get('steals') + row.get('charges_drawn') if row.get('steals') is not None and row.get('charges_drawn') is not None else None,
            'team': lambda row, ctx: row.get('steals') + row.get('charges_drawn') if row.get('steals') is not None and row.get('charges_drawn') is not None else None,
            'all_teams': lambda row, ctx: row.get('steals') + row.get('charges_drawn') if row.get('steals') is not None and row.get('charges_drawn') is not None else None
        }
    },
    'fls': {
        'description': 'Personal Fouls',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('fouls',)},
            'team': {'fields': ('fouls',)},
            'all_teams': {'fields': ('fouls',)},
            'opponents': {'fields': ('opp_fouls',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('fouls'),
            'team': lambda row, ctx: row.get('fouls'),
            'all_teams': lambda row, ctx: row.get('fouls'),
            'opponents': lambda row, ctx: row.get('opp_fouls')
        }
    },
    'w%': {
        'description': 'Win percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_teams', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('wins', 'games')},
            'team': {'fields': ('wins', 'games')},
            'all_teams': {'fields': ('wins', 'games')},
        },
        'values': {
            'player': lambda row, ctx: row.get('wins') / row.get('games') if row.get('wins') is not None and row.get('games') else None,
            'team': lambda row, ctx: row.get('wins') / row.get('games') if row.get('wins') is not None and row.get('games') else None,
            'all_teams': lambda row, ctx: row.get('wins') / row.get('games') if row.get('wins') is not None and row.get('games') else None
        }
    },
    'ortg': {
        'description': 'Team Offensive Rating When On Court',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('o_rtg_x10',)},
            'team': {'fields': ('o_rtg_x10',)},
            'all_teams': {'fields': ('o_rtg_x10',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('o_rtg_x10') / 10 if row.get('o_rtg_x10') is not None else None,
            'team': lambda row, ctx: row.get('o_rtg_x10') / 10 if row.get('o_rtg_x10') is not None else None,
            'all_teams': lambda row, ctx: row.get('o_rtg_x10') / 10 if row.get('o_rtg_x10') is not None else None
        }
    },
    'drtg': {
        'description': 'Team Defensive Rating When On Court',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_rtg_x10',)},
            'team': {'fields': ('d_rtg_x10',)},
            'all_teams': {'fields': ('d_rtg_x10',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('d_rtg_x10') / 10 if row.get('d_rtg_x10') is not None else None,
            'team': lambda row, ctx: row.get('d_rtg_x10') / 10 if row.get('d_rtg_x10') is not None else None,
            'all_teams': lambda row, ctx: row.get('d_rtg_x10') / 10 if row.get('d_rtg_x10') is not None else None
        }
    },
    'nooo': {
        'description': 'Net Offensive On/Off Team Rating',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('o_rtg_x10', 'off_o_rtg_x10')},
        },
        'values': {
            'player': lambda row, ctx: (row.get('o_rtg_x10') / 10) - (row.get('off_o_rtg_x10') / 10) if row.get('o_rtg_x10') is not None and row.get('off_o_rtg_x10') is not None else None
        }
    },
    'ndoo': {
        'description': 'Net Defensive on/off Team Rating',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('d_rtg_x10', 'off_d_rtg_x10')},
        },
        'values': {
            'player': lambda row, ctx: (row.get('d_rtg_x10') / 10) - (row.get('off_d_rtg_x10') / 10) if row.get('d_rtg_x10') is not None and row.get('off_d_rtg_x10') is not None else None
        }
    },
    'ID': {
        'description': 'The Glass Entity ID',
        'sections': ['identity'],
        'subsection': None,
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': 0,
        'width_class': 'auto',
        'link': None,
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'inputs': {
            'player': {'fields': ('the_glass_id',)},
            'team': {'fields': ('the_glass_id',)},
            'all_teams': {'fields': ('the_glass_id',)},
        },
        'values': {
            'player': lambda row, ctx: row.get('the_glass_id'),
            'team': lambda row, ctx: row.get('the_glass_id'),
            'all_teams': lambda row, ctx: row.get('the_glass_id')
        }
    }
}