"""
Shoot the Sheet - Publish Column Registry

View column definitions (VIEW_COLUMNS) and the field-derivation logic that
maps display columns back to database column references.
"""

from typing import Any, Callable, Dict, List, Literal, Tuple, TypedDict, Union

from src.publish.lib.formulas import (
    calculate_age,
    lookup,
    PublishContext,
    PublishRow,
    seasons_in_query,
    team_average,
)

# ============================================================================
# COLUMN DEFINITIONS
# ============================================================================

# Valid attribute value sets (co-located with the schema they constrain)
SheetName = Literal['all_teams', 'all_players', 'individual_team']
StatsMode = Literal['basic', 'advanced', 'both']
FormatType = Literal['text', 'number', 'percentage', 'measurement']
AlignType = Literal['left', 'center']

_VALID_SECTIONS = frozenset({
    'entities', 'profile', 'evaluation',
    'current_stats', 'historical_stats', 'postseason_stats', 'identity',
})
_VALID_SUBSECTIONS = frozenset({
    'rates', 'scoring', 'ball_management', 'rebounding',
    'distance', 'defense', 'opponent', 'team_ratings', 'nba',
    'League', 'Player',
})
_VALID_VIEWS = frozenset({'all_teams', 'all_players', 'individual_team'})
_VALID_STATS_MODES = frozenset({'basic', 'advanced', 'both'})
_VALID_LINKS = frozenset({'team_link', None})
_VALID_FORMATS = frozenset({'text', 'number', 'percentage', 'measurement'})
_VALID_WIDTH_CLASSES = frozenset({
    'auto', 'measurement', 'four_char', 'four_char_dec',
    'three_char_dec', 'two_char', 'two_char_dec'
})
_VALID_WIDTH_CLASS_TYPES = (str, int)
_VALID_LEAGUES = frozenset({'NBA', 'ncaa'})

_VALID_ALIGNS = frozenset({'left', 'center'})
_VALID_EMPHASIS = frozenset({'bold', None})


class ValueDef(TypedDict):
    fields: Tuple[str, ...]
    fn: Callable[[PublishRow, PublishContext], Any]


class ViewColumnDef(TypedDict):
    description: str
    sections: List[str]
    subsection: Union[str, None]
    sheets: List[SheetName]
    stats_mode: StatsMode
    percentile: Union[str, None]
    editable: Union[List[str], None]
    rate_domain: Union[str, None]
    format: FormatType
    decimal_places: Union[int, None]
    width_class: Union[str, int]
    link: Union[str, None]
    leagues: List[str]
    team_row_display: Union[str, None]
    default: Union[str, int, float, None]
    align: AlignType
    emphasis: Union[str, None]
    font_size: int
    values: Dict[str, ValueDef]

VIEW_COLUMNS: Dict[str, ViewColumnDef] = {
    'players': {
        'description': 'Player Name',
        'sections': ['entities'],
        'subsection': None,
        'sheets': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'auto',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'left',
        'emphasis': 'bold',
        'font_size': 10,
        'values': {
            'player': {'fields': ('p.name',), 'fn': lambda row, ctx: row['name']},
            'team': {'fields': (), 'fn': lambda row, ctx: 'TEAM'},
            'opponents': {'fields': (), 'fn': lambda row, ctx: 'OPPONENTS'}
        }
    },
    'teams': {
        'description': 'Team Name',
        'sections': ['entities'],
        'subsection': None,
        'sheets': ['all_teams'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'auto',
        'link': 'team_link',
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'left',
        'emphasis': 'bold',
        'font_size': 10,
        'values': {
            'all_teams': {'fields': ('t.name',), 'fn': lambda row, ctx: row['name']}
        }
    },
    'team': {
        'description': 'Team Abbreviation',
        'sections': ['profile'],
        'subsection': 'League',
        'sheets': ['all_players'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'four_char',
        'link': 'team_link',
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.team_id',), 'fn': lambda row, ctx: lookup(row['team_id'], 'teams', 'abbr', ctx)}
        }
    },
    'conf': {
        'description': 'Conference',
        'sections': ['profile'],
        'subsection': 'League',
        'sheets': ['all_teams'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'four_char',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'all_teams': {'fields': ('t.conf',), 'fn': lambda row, ctx: row['conf']}
        }
    },
    'J#': {
        'description': 'Jersey Number',
        'sections': ['profile'],
        'subsection': 'League',
        'sheets': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'two_char',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('tr.jersey_num',), 'fn': lambda row, ctx: row['jersey_num']}
        }
    },
    'exp': {
        'description': 'Seasons with Playing Experience',
        'sections': ['profile'],
        'subsection': 'League',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'two_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': 'average',
        'default': '0',
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.seasons_exp',), 'fn': lambda row, ctx: row['seasons_exp']},
            'team': {'fields': ('p.seasons_exp',), 'fn': lambda row, ctx: team_average(lambda p, c: p['seasons_exp'], ctx)},
            'all_teams': {'fields': ('p.seasons_exp',), 'fn': lambda row, ctx: team_average(lambda p, c: p['seasons_exp'], ctx)}
        }
    },
    'age': {
        'description': 'Age',
        'sections': ['profile'],
        'subsection': 'Player',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.birthdate',), 'fn': lambda row, ctx: calculate_age(row['birthdate'])},
            'team': {'fields': ('p.birthdate',), 'fn': lambda row, ctx: team_average(lambda p, c: calculate_age(p['birthdate']), ctx)},
            'all_teams': {'fields': ('p.birthdate',), 'fn': lambda row, ctx: team_average(lambda p, c: calculate_age(p['birthdate']), ctx)}
        },
    },
    'ht': {
        'description': 'Height in Feet\'Inches"',
        'sections': ['profile'],
        'subsection': 'Player',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'measurement',
        'decimal_places': 1,
        'width_class': 'measurement',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.height_ins_with_shoes',), 'fn': lambda row, ctx: row['height_ins_with_shoes']},
            'team': {'fields': ('p.height_ins_with_shoes',), 'fn': lambda row, ctx: team_average(lambda p, c: p['height_ins_with_shoes'], ctx)},
            'all_teams': {'fields': ('p.height_ins_with_shoes',), 'fn': lambda row, ctx: team_average(lambda p, c: p['height_ins_with_shoes'], ctx)}
        }
    },
    'wt': {
        'description': 'Weight in Pounds',
        'sections': ['profile'],
        'subsection': 'Player',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.weight_lbs',), 'fn': lambda row, ctx: row['weight_lbs']},
            'team': {'fields': ('p.weight_lbs',), 'fn': lambda row, ctx: team_average(lambda p, c: p['weight_lbs'], ctx)},
            'all_teams': {'fields': ('p.weight_lbs',), 'fn': lambda row, ctx: team_average(lambda p, c: p['weight_lbs'], ctx)}
        }
    },
    'ws': {
        'description': 'Wingspan in Feet\'Inches" (Editable)',
        'sections': ['profile'],
        'subsection': 'Player',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': ['player'],
        'rate_domain': None,
        'format': 'measurement',
        'decimal_places': 1,
        'width_class': 'measurement',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.wingspan_ins',), 'fn': lambda row, ctx: row['wingspan_ins']},
            'team': {'fields': ('p.wingspan_ins',), 'fn': lambda row, ctx: team_average(lambda p, c: p['wingspan_ins'], ctx)},
            'all_teams': {'fields': ('p.wingspan_ins',), 'fn': lambda row, ctx: team_average(lambda p, c: p['wingspan_ins'], ctx)}
        }
    },
    '🖐️': {
        'description': 'Handedness (Editable)',
        'sections': ['profile'],
        'subsection': 'Player',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': ['player'],
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'two_char',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.hand',), 'fn': lambda row, ctx: row['hand']}
        }
    },
    'notes': {
        'description': 'Personal thoughts, observations, findings, etc (Editable)',
        'sections': ['evaluation'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': ['player', 'individual_team', 'all_teams'],
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 500,
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': 'editable',
        'default': None,
        'align': 'left',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.notes',), 'fn': lambda row, ctx: row['notes']},
            'team': {'fields': ('t.notes',), 'fn': lambda row, ctx: row['notes']},
            'all_teams': {'fields': ('t.notes',), 'fn': lambda row, ctx: row['notes']}
        }
    },
    'szn': {
        'description': 'Seasons Played',
        'sections': ['historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': (), 'fn': lambda row, ctx: seasons_in_query(ctx)},
            'team': {'fields': (), 'fn': lambda row, ctx: seasons_in_query(ctx)},
            'all_teams': {'fields': (), 'fn': lambda row, ctx: seasons_in_query(ctx)}
        }
    },
    'gms': {
        'description': 'Games Played per Season',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.games',), 'fn': lambda row, ctx: row['games'] / seasons_in_query(ctx)},
            'team': {'fields': ('s.games',), 'fn': lambda row, ctx: row['games'] / seasons_in_query(ctx)},
            'all_teams': {'fields': ('s.games',), 'fn': lambda row, ctx: row['games'] / seasons_in_query(ctx)}
        },
    },
    'min': {
        'description': 'Minutes Played per Game',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': 'team_value',
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.mins_x10', 's.games'), 'fn': lambda row, ctx: (row['mins_x10'] / 10) / row['games']},
            'team': {'fields': ('s.mins_x10', 's.games'), 'fn': lambda row, ctx: (row['mins_x10'] / 10) / row['games']},
            'all_teams': {'fields': ('s.mins_x10', 's.games'), 'fn': lambda row, ctx: (row['mins_x10'] / 10) / row['games']}
        }
    },
    'pace': {
        'description': 'Possessions per 40 Mins',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.possessions', 's.mins_x10'), 'fn': lambda row, ctx: (row['possessions'] * 40) / (row['mins_x10'] / 10)},
            'team': {'fields': ('s.possessions', 's.mins_x10'), 'fn': lambda row, ctx: (row['possessions'] * 40) / (row['mins_x10'] / 10)},
            'all_teams': {'fields': ('s.possessions', 's.mins_x10'), 'fn': lambda row, ctx: (row['possessions'] * 40) / (row['mins_x10'] / 10)}
        }
    },
    'pts': {
        'description': 'Points',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fg2m', 's.fg3m', 's.ftm'), 'fn': lambda row, ctx: (row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']},
            'team': {'fields': ('s.fg2m', 's.fg3m', 's.ftm'), 'fn': lambda row, ctx: (row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']},
            'all_teams': {'fields': ('s.fg2m', 's.fg3m', 's.ftm'), 'fn': lambda row, ctx: (row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']},
            'opponents': {'fields': ('s.opp_fg2m', 's.opp_fg3m', 's.opp_ftm'), 'fn': lambda row, ctx: (row['opp_fg2m'] * 2) + (row['opp_fg3m'] * 3) + row['opp_ftm']}
        }
    },
    'p/ta': {
        'description': 'Points per "True" FGA (FGA + FTA per FT Trip Estimation) or TS% * 2',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fg2m', 's.fg3m', 's.ftm', 's.fg2a', 's.fg3a', 's.fta'), 'fn': lambda row, ctx: ((row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44))},
            'team': {'fields': ('s.fg2m', 's.fg3m', 's.ftm', 's.fg2a', 's.fg3a', 's.fta'), 'fn': lambda row, ctx: ((row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44))},
            'all_teams': {'fields': ('s.fg2m', 's.fg3m', 's.ftm', 's.fg2a', 's.fg3a', 's.fta'), 'fn': lambda row, ctx: ((row['fg2m'] * 2) + (row['fg3m'] * 3) + row['ftm']) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44))},
            'opponents': {'fields': ('s.opp_fg2m', 's.opp_fg3m', 's.opp_ftm', 's.opp_fg2a', 's.opp_fg3a', 's.opp_fta'), 'fn': lambda row, ctx: ((row['opp_fg2m'] * 2) + (row['opp_fg3m'] * 3) + row['opp_ftm']) / (row['opp_fg2a'] + row['opp_fg3a'] + (row['opp_fta'] * 0.44))}
        }
    },
    '2a': {
        'description': 'Two-Point FGA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fg2a',), 'fn': lambda row, ctx: row['fg2a']},
            'team': {'fields': ('s.fg2a',), 'fn': lambda row, ctx: row['fg2a']},
            'all_teams': {'fields': ('s.fg2a',), 'fn': lambda row, ctx: row['fg2a']},
            'opponents': {'fields': ('s.opp_fg2a',), 'fn': lambda row, ctx: row['opp_fg2a']}
        }
    },
    'p/2': {
        'description': 'Points per 2A',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fg2m', 's.fg2a'), 'fn': lambda row, ctx: 2 * (row['fg2m'] / row['fg2a'])},
            'team': {'fields': ('s.fg2m', 's.fg2a'), 'fn': lambda row, ctx: 2 * (row['fg2m'] / row['fg2a'])},
            'all_teams': {'fields': ('s.fg2m', 's.fg2a'), 'fn': lambda row, ctx: 2 * (row['fg2m'] / row['fg2a'])},
            'opponents': {'fields': ('s.opp_fg2m', 's.opp_fg2a'), 'fn': lambda row, ctx: 2 * (row['opp_fg2m'] / row['opp_fg2a'])}
        }
    },
    'ora': {
        'description': 'Open 2A at the Rim (Closest Defender Beyond 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.open_rim_fga',), 'fn': lambda row, ctx: row['open_rim_fga']},
            'team': {'fields': ('t.open_rim_fga',), 'fn': lambda row, ctx: row['open_rim_fga']},
            'all_teams': {'fields': ('t.open_rim_fga',), 'fn': lambda row, ctx: row['open_rim_fga']}
        }
    },
    'p/or': {
        'description': 'Points per Open 2A at the Rim (Closest Defender Beyond 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.open_rim_fgm', 'p.open_rim_fga'), 'fn': lambda row, ctx: 2 * (row['open_rim_fgm'] / row['open_rim_fga'])},
            'team': {'fields': ('t.open_rim_fgm', 't.open_rim_fga'), 'fn': lambda row, ctx: 2 * (row['open_rim_fgm'] / row['open_rim_fga'])},
            'all_teams': {'fields': ('t.open_rim_fgm', 't.open_rim_fga'), 'fn': lambda row, ctx: 2 * (row['open_rim_fgm'] / row['open_rim_fga'])}
        }
    },
    'cra': {
        'description': 'Contested 2A at the Rim (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.cont_rim_fga',), 'fn': lambda row, ctx: row['cont_rim_fga']},
            'team': {'fields': ('t.cont_rim_fga',), 'fn': lambda row, ctx: row['cont_rim_fga']},
            'all_teams': {'fields': ('t.cont_rim_fga',), 'fn': lambda row, ctx: row['cont_rim_fga']}
        }
    },
    'p/cr': {
        'description': 'Points per Contested 2A at the Rim (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.cont_rim_fgm', 'p.cont_rim_fga'), 'fn': lambda row, ctx: 2 * (row['cont_rim_fgm'] / row['cont_rim_fga'])},
            'team': {'fields': ('t.cont_rim_fgm', 't.cont_rim_fga'), 'fn': lambda row, ctx: 2 * (row['cont_rim_fgm'] / row['cont_rim_fga'])},
            'all_teams': {'fields': ('t.cont_rim_fgm', 't.cont_rim_fga'), 'fn': lambda row, ctx: 2 * (row['cont_rim_fgm'] / row['cont_rim_fga'])}
        }
    },
    'uar': {
        'description': 'Unassisted 2A Made at the Rim (Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.unassisted_rim_fgm',), 'fn': lambda row, ctx: row['unassisted_rim_fgm']},
            'team': {'fields': ('s.unassisted_rim_fgm',), 'fn': lambda row, ctx: row['unassisted_rim_fgm']},
            'all_teams': {'fields': ('s.unassisted_rim_fgm',), 'fn': lambda row, ctx: row['unassisted_rim_fgm']}
        }
    },
    'oma': {
        'description': 'Open 2A in the Mid-Range (Closest Defender Beyond 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.cont_fg2a', 'p.cont_rim_fga'), 'fn': lambda row, ctx: row['cont_fg2a'] - row['cont_rim_fga']},
            'team': {'fields': ('s.cont_fg2a', 't.cont_rim_fga'), 'fn': lambda row, ctx: row['cont_fg2a'] - row['cont_rim_fga']},
            'all_teams': {'fields': ('s.cont_fg2a', 't.cont_rim_fga'), 'fn': lambda row, ctx: row['cont_fg2a'] - row['cont_rim_fga']}
        }
    },
    'p/om': {
        'description': 'Points per Open 2A in the Mid-Range (Closest Defender Beyond 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.open_fg2m', 'p.open_rim_fgm', 's.open_fg2a', 'p.open_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['open_fg2m'] - row['open_rim_fgm']) / (row['open_fg2a'] - row['open_rim_fga']))},
            'team': {'fields': ('s.open_fg2m', 't.open_rim_fgm', 's.open_fg2a', 't.open_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['open_fg2m'] - row['open_rim_fgm']) / (row['open_fg2a'] - row['open_rim_fga']))},
            'all_teams': {'fields': ('s.open_fg2m', 't.open_rim_fgm', 's.open_fg2a', 't.open_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['open_fg2m'] - row['open_rim_fgm']) / (row['open_fg2a'] - row['open_rim_fga']))}
        }
    },
    'cma': {
        'description': 'Contested 2A in the Mid-Range (Closest Defender Within 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.cont_fg2a', 'p.cont_rim_fga'), 'fn': lambda row, ctx: row['cont_fg2a'] - row['cont_rim_fga']},
            'team': {'fields': ('s.cont_fg2a', 't.cont_rim_fga'), 'fn': lambda row, ctx: row['cont_fg2a'] - row['cont_rim_fga']},
            'all_teams': {'fields': ('s.cont_fg2a', 't.cont_rim_fga'), 'fn': lambda row, ctx: row['cont_fg2a'] - row['cont_rim_fga']}
        }
    },
    'p/cm': {
        'description': 'Points per Contested 2A in the Mid-Range (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.cont_fg2m', 'p.cont_rim_fgm', 's.cont_fg2a', 'p.cont_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['cont_fg2m'] - row['cont_rim_fgm']) / (row['cont_fg2a'] - row['cont_rim_fga']))},
            'team': {'fields': ('s.cont_fg2m', 't.cont_rim_fgm', 's.cont_fg2a', 't.cont_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['cont_fg2m'] - row['cont_rim_fgm']) / (row['cont_fg2a'] - row['cont_rim_fga']))},
            'all_teams': {'fields': ('s.cont_fg2m', 't.cont_rim_fgm', 's.cont_fg2a', 't.cont_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['cont_fg2m'] - row['cont_rim_fgm']) / (row['cont_fg2a'] - row['cont_rim_fga']))}
        }
    },
    'uam': {
        'description': 'Unassisted 2A Made in the Mid-Range (Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.unassisted_fg2m', 's.unassisted_rim_fgm'), 'fn': lambda row, ctx: row['unassisted_fg2m'] - row['unassisted_rim_fgm']},
            'team': {'fields': ('s.unassisted_fg2m', 's.unassisted_rim_fgm'), 'fn': lambda row, ctx: row['unassisted_fg2m'] - row['unassisted_rim_fgm']},
            'all_teams': {'fields': ('t.unassisted_fgm', 's.unassisted_rim_fgm'), 'fn': lambda row, ctx: row['unassisted_fgm'] - row['unassisted_rim_fgm']}
        }
    },
    '3a': {
        'description': 'Three-Point FGA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fg3a',), 'fn': lambda row, ctx: row['fg3a']},
            'team': {'fields': ('s.fg3a',), 'fn': lambda row, ctx: row['fg3a']},
            'all_teams': {'fields': ('s.fg3a',), 'fn': lambda row, ctx: row['fg3a']},
            'opponents': {'fields': ('s.opp_fg3a',), 'fn': lambda row, ctx: row['opp_fg3a']}
        }
    },
    'p/3': {
        'description': 'Points per 3A',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fg3m', 's.fg3a'), 'fn': lambda row, ctx: 3 * (row['fg3m'] / row['fg3a'])},
            'team': {'fields': ('s.fg3m', 's.fg3a'), 'fn': lambda row, ctx: 3 * (row['fg3m'] / row['fg3a'])},
            'all_teams': {'fields': ('s.fg3m', 's.fg3a'), 'fn': lambda row, ctx: 3 * (row['fg3m'] / row['fg3a'])},
            'opponents': {'fields': ('s.opp_fg3m', 's.opp_fg3a'), 'fn': lambda row, ctx: 3 * (row['opp_fg3m'] / row['opp_fg3a'])}
        }
    },
    'o3a': {
        'description': 'Open 3A (Closest Defender Beyond 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.open_fg3a',), 'fn': lambda row, ctx: row['open_fg3a']},
            'team': {'fields': ('s.open_fg3a',), 'fn': lambda row, ctx: row['open_fg3a']},
            'all_teams': {'fields': ('s.open_fg3a',), 'fn': lambda row, ctx: row['open_fg3a']}
        }
    },
    'p/o3': {
        'description': 'Points per Open 3A (Closest Defender Beyond 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.open_fg3m', 's.open_fg3a'), 'fn': lambda row, ctx: 3 * (row['open_fg3m'] / row['open_fg3a'])},
            'team': {'fields': ('s.open_fg3m', 's.open_fg3a'), 'fn': lambda row, ctx: 3 * (row['open_fg3m'] / row['open_fg3a'])},
            'all_teams': {'fields': ('s.open_fg3m', 's.open_fg3a'), 'fn': lambda row, ctx: 3 * (row['open_fg3m'] / row['open_fg3a'])}
        }
    },
    'c3a': {
        'description': 'Contested 3A (Closest Defender Within 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.cont_fg3a',), 'fn': lambda row, ctx: row['cont_fg3a']},
            'team': {'fields': ('s.cont_fg3a',), 'fn': lambda row, ctx: row['cont_fg3a']},
            'all_teams': {'fields': ('s.cont_fg3a',), 'fn': lambda row, ctx: row['cont_fg3a']}
        }
    },
    'p/c3': {
        'description': 'Points per Contested 3A (Closest Defender Within 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.cont_fg3m', 's.cont_fg3a'), 'fn': lambda row, ctx: 3 * (row['cont_fg3m'] / row['cont_fg3a'])},
            'team': {'fields': ('s.cont_fg3m', 's.cont_fg3a'), 'fn': lambda row, ctx: 3 * (row['cont_fg3m'] / row['cont_fg3a'])},
            'all_teams': {'fields': ('s.cont_fg3m', 's.cont_fg3a'), 'fn': lambda row, ctx: 3 * (row['cont_fg3m'] / row['cont_fg3a'])}
        }
    },
    'ua3': {
        'description': 'Unassisted 3A Made',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.unassisted_fg3m',), 'fn': lambda row, ctx: row['unassisted_fg3m']},
            'team': {'fields': ('s.unassisted_fg3m',), 'fn': lambda row, ctx: row['unassisted_fg3m']},
            'all_teams': {'fields': ('s.unassisted_fg3m',), 'fn': lambda row, ctx: row['unassisted_fg3m']}
        }
    },
    'tftr': {
        'description': '"True" Free throw Rate (FT Trip Estimation / (FGA + FT Trip Estimation))',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fta', 's.fg2a', 's.fg3a'), 'fn': lambda row, ctx: (row['fta'] * 0.44) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44))},
            'team': {'fields': ('s.fta', 's.fg2a', 's.fg3a'), 'fn': lambda row, ctx: (row['fta'] * 0.44) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44))},
            'all_teams': {'fields': ('s.fta', 's.fg2a', 's.fg3a'), 'fn': lambda row, ctx: (row['fta'] * 0.44) / (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44))},
            'opponents': {'fields': ('s.opp_fta', 's.opp_fg2a', 's.opp_fg3a'), 'fn': lambda row, ctx: (row['opp_fta'] * 0.44) / (row['opp_fg2a'] + row['opp_fg3a'] + (row['opp_fta'] * 0.44))}
        }
    },
    'p/ft': {
        'description': 'Points per FTA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.ftm', 's.fta'), 'fn': lambda row, ctx: row['ftm'] / row['fta']},
            'team': {'fields': ('s.ftm', 's.fta'), 'fn': lambda row, ctx: row['ftm'] / row['fta']},
            'all_teams': {'fields': ('s.ftm', 's.fta'), 'fn': lambda row, ctx: row['ftm'] / row['fta']},
            'opponents': {'fields': ('s.opp_ftm', 's.opp_fta'), 'fn': lambda row, ctx: row['opp_ftm'] / row['opp_fta']}
        }
    },
    'dnk': {
        'description': 'Dunks',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.dunks',), 'fn': lambda row, ctx: row['dunks']},
            'team': {'fields': ('s.dunks',), 'fn': lambda row, ctx: row['dunks']},
            'all_teams': {'fields': ('s.dunks',), 'fn': lambda row, ctx: row['dunks']}
        }
    },
    'tou': {
        'description': 'Instances of Holding the Ball',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.touches',), 'fn': lambda row, ctx: row['touches']},
            'team': {'fields': ('s.touches',), 'fn': lambda row, ctx: row['touches']},
            'all_teams': {'fields': ('s.touches',), 'fn': lambda row, ctx: row['touches']}
        }
    },
    'spt': {
        'description': 'Seconds per Touch',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'two_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.time_on_ball', 's.touches'), 'fn': lambda row, ctx: (60 * row['time_on_ball']) / row['touches']},
            'team': {'fields': ('s.time_on_ball', 's.touches'), 'fn': lambda row, ctx: (60 * row['time_on_ball']) / row['touches']},
            'all_teams': {'fields': ('s.time_on_ball', 's.touches'), 'fn': lambda row, ctx: (60 * row['time_on_ball']) / row['touches']}
        }
    },
    '%trs': {
        'description': 'Percentage of Touches Resulting in a Shot',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fg2a', 's.fg3a', 's.fta', 's.touches'), 'fn': lambda row, ctx: (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)) / row['touches']},
            'team': {'fields': ('s.fg2a', 's.fg3a', 's.fta', 's.touches'), 'fn': lambda row, ctx: (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)) / row['touches']},
            'all_teams': {'fields': ('s.fg2a', 's.fg3a', 's.fta', 's.touches'), 'fn': lambda row, ctx: (row['fg2a'] + row['fg3a'] + (row['fta'] * 0.44)) / row['touches']}
        }
    },
    '%trp': {
        'description': 'Percentage of Touches Resulting in a Pass',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.passes', 's.touches'), 'fn': lambda row, ctx: row['passes'] / row['touches']},
            'team': {'fields': ('s.passes', 's.touches'), 'fn': lambda row, ctx: row['passes'] / row['touches']},
            'all_teams': {'fields': ('s.passes', 's.touches'), 'fn': lambda row, ctx: row['passes'] / row['touches']}
        }
    },
    '%trt': {
        'description': 'Percentage of Touches Resulting in a Turnover',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.turnovers', 's.touches'), 'fn': lambda row, ctx: row['turnovers'] / row['touches']},
            'team': {'fields': ('s.turnovers', 's.touches'), 'fn': lambda row, ctx: row['turnovers'] / row['touches']},
            'all_teams': {'fields': ('s.turnovers', 's.touches'), 'fn': lambda row, ctx: row['turnovers'] / row['touches']}
        }
    },
    'ast': {
        'description': 'Assists',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.assists',), 'fn': lambda row, ctx: row['assists']},
            'team': {'fields': ('s.assists',), 'fn': lambda row, ctx: row['assists']},
            'all_teams': {'fields': ('s.assists',), 'fn': lambda row, ctx: row['assists']},
            'opponents': {'fields': ('s.opp_assists',), 'fn': lambda row, ctx: row['opp_assists']}
        }
    },
    'past': {
        'description': 'Potential Assists (Passes that lead to a FGA)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'sec_assists',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.pot_assists',), 'fn': lambda row, ctx: row['pot_assists']},
            'team': {'fields': ('s.pot_assists',), 'fn': lambda row, ctx: row['pot_assists']},
            'all_teams': {'fields': ('s.pot_assists',), 'fn': lambda row, ctx: row['pot_assists']}
        }
    },
    '2ast': {
        'description': 'Secondary Assists (Passes that Lead to an Assist)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'sec_assists',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.sec_assists',), 'fn': lambda row, ctx: row['sec_assists']},
            'team': {'fields': ('s.sec_assists',), 'fn': lambda row, ctx: row['sec_assists']},
            'all_teams': {'fields': ('s.sec_assists',), 'fn': lambda row, ctx: row['sec_assists']}
        }
    },
    'tov': {
        'description': 'Turnovers',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.turnovers',), 'fn': lambda row, ctx: row['turnovers']},
            'team': {'fields': ('s.turnovers',), 'fn': lambda row, ctx: row['turnovers']},
            'all_teams': {'fields': ('s.turnovers',), 'fn': lambda row, ctx: row['turnovers']},
            'opponents': {'fields': ('s.opp_turnovers',), 'fn': lambda row, ctx: row['opp_turnovers']}
        }
    },
    'or%': {
        'description': 'Offensive Rebound Percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.o_reb_pct_x1000',), 'fn': lambda row, ctx: row['o_reb_pct_x1000'] / 1000},
            'team': {'fields': ('s.o_reb_pct_x1000',), 'fn': lambda row, ctx: row['o_reb_pct_x1000'] / 1000},
            'all_teams': {'fields': ('s.o_reb_pct_x1000',), 'fn': lambda row, ctx: row['o_reb_pct_x1000'] / 1000}
        }
    },
    'cor%': {
        'description': 'Contested Offensive Rebound Percentage (Percentage of Offensive Rebounds that are Contested)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.cont_o_rebs', 's.o_rebs'), 'fn': lambda row, ctx: row['cont_o_rebs'] / row['o_rebs']},
            'team': {'fields': ('s.cont_o_rebs', 's.o_rebs'), 'fn': lambda row, ctx: row['cont_o_rebs'] / row['o_rebs']},
            'all_teams': {'fields': ('s.cont_o_rebs', 's.o_rebs'), 'fn': lambda row, ctx: row['cont_o_rebs'] / row['o_rebs']}
        }
    },
    'dr%': {
        'description': 'Defensive Rebound Percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.d_reb_pct_x1000',), 'fn': lambda row, ctx: row['d_reb_pct_x1000'] / 1000},
            'team': {'fields': ('s.d_reb_pct_x1000',), 'fn': lambda row, ctx: row['d_reb_pct_x1000'] / 1000},
            'all_teams': {'fields': ('s.d_reb_pct_x1000',), 'fn': lambda row, ctx: row['d_reb_pct_x1000'] / 10}
        }
    },
    'cdr%': {
        'description': 'Contested Defensive Rebound Percentage (Percentage of Defensive Rebounds that are Contested)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.cont_d_rebs', 's.d_rebs'), 'fn': lambda row, ctx: row['cont_d_rebs'] / row['d_rebs']},
            'team': {'fields': ('s.cont_d_rebs', 's.d_rebs'), 'fn': lambda row, ctx: row['cont_d_rebs'] / row['d_rebs']},
            'all_teams': {'fields': ('s.cont_d_rebs', 's.d_rebs'), 'fn': lambda row, ctx: row['cont_d_rebs'] / row['d_rebs']}
        }
    },
    'pbs': {
        'description': 'Putbacks (FGM immediately following an offensive rebound)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.putbacks',), 'fn': lambda row, ctx: row['putbacks']},
            'team': {'fields': ('s.putbacks',), 'fn': lambda row, ctx: row['putbacks']},
            'all_teams': {'fields': ('s.putbacks',), 'fn': lambda row, ctx: row['putbacks']}
        }
    },
    'odst': {
        'description': 'Offensive Distance Traveled in Miles',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distance',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.o_dist_x10',), 'fn': lambda row, ctx: row['o_dist_x10'] / 10},
            'team': {'fields': ('s.o_dist_x10',), 'fn': lambda row, ctx: row['o_dist_x10'] / 10},
            'all_teams': {'fields': ('s.o_dist_x10',), 'fn': lambda row, ctx: row['o_dist_x10'] / 10}
        }
    },
    'ddst': {
        'description': 'Defensive Distance Traveled in Miles',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distance',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.d_dist_x10',), 'fn': lambda row, ctx: row['d_dist_x10'] / 10},
            'team': {'fields': ('s.d_dist_x10',), 'fn': lambda row, ctx: row['d_dist_x10'] / 10},
            'all_teams': {'fields': ('s.d_dist_x10',), 'fn': lambda row, ctx: row['d_dist_x10'] / 10}
        }
    },
    'dra': {
        'description': 'Defended 2A at the Rim (Closest Defender for FGA Within 5 Feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.d_rim_fga',), 'fn': lambda row, ctx: row['d_rim_fga']},
            'team': {'fields': ('t.d_rim_fga',), 'fn': lambda row, ctx: row['d_rim_fga']},
            'all_teams': {'fields': ('t.d_rim_fga',), 'fn': lambda row, ctx: row['d_rim_fga']}
        }
    },
    'p/dr': {
        'description': 'Points Allowed per Defended FGA at the Rim (Closest Defender for FGA Within 5 Feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.d_rim_fgm', 'p.d_rim_fga'), 'fn': lambda row, ctx: 2 * (row['d_rim_fgm'] / row['d_rim_fga'])},
            'team': {'fields': ('t.d_rim_fgm', 't.d_rim_fga'), 'fn': lambda row, ctx: 2 * (row['d_rim_fgm'] / row['d_rim_fga'])},
            'all_teams': {'fields': ('t.d_rim_fgm', 't.d_rim_fga'), 'fn': lambda row, ctx: 2 * (row['d_rim_fgm'] / row['d_rim_fga'])}
        }
    },
    'dma': {
        'description': 'Defended 2A in the Mid-Range (Closest Defender for FGA Beyond 5 Feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.d_fg2a', 'p.d_rim_fga'), 'fn': lambda row, ctx: row['d_fg2a'] - row['d_rim_fga']},
            'team': {'fields': ('s.d_fg2a', 't.d_rim_fga'), 'fn': lambda row, ctx: row['d_fg2a'] - row['d_rim_fga']},
            'all_teams': {'fields': ('s.d_fg2a', 't.d_rim_fga'), 'fn': lambda row, ctx: row['d_fg2a'] - row['d_rim_fga']}
        }
    },
    'p/dm': {
        'description': 'Points Allowed per Defended FGA in the Mid-Range (Closest Defender for FGA Beyond 5 Feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.d_fg2m', 'p.d_rim_fgm', 's.d_fg2a', 'p.d_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['d_fg2m'] - row['d_rim_fgm']) / (row['d_fg2a'] - row['d_rim_fga']))},
            'team': {'fields': ('s.d_fg2m', 't.d_rim_fgm', 's.d_fg2a', 't.d_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['d_fg2m'] - row['d_rim_fgm']) / (row['d_fg2a'] - row['d_rim_fga']))},
            'all_teams': {'fields': ('s.d_fg2m', 't.d_rim_fgm', 's.d_fg2a', 't.d_rim_fga'), 'fn': lambda row, ctx: 2 * ((row['d_fg2m'] - row['d_rim_fgm']) / (row['d_fg2a'] - row['d_rim_fga']))}
        }
    },
    'd3a': {
        'description': 'Defended 3A (Closest Defender)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'tracking',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.d_fg3a',), 'fn': lambda row, ctx: row['d_fg3a']},
            'team': {'fields': ('s.d_fg3a',), 'fn': lambda row, ctx: row['d_fg3a']},
            'all_teams': {'fields': ('s.d_fg3a',), 'fn': lambda row, ctx: row['d_fg3a']}
        }
    },
    'p/d3': {
        'description': 'Points Allowed per Defended 3A (Closest Defender)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.d_fg3m', 's.d_fg3a'), 'fn': lambda row, ctx: 3 * (row['d_fg3m'] / row['d_fg3a'])},
            'team': {'fields': ('s.d_fg3m', 's.d_fg3a'), 'fn': lambda row, ctx: 3 * (row['d_fg3m'] / row['d_fg3a'])},
            'all_teams': {'fields': ('s.d_fg3m', 's.d_fg3a'), 'fn': lambda row, ctx: 3 * (row['d_fg3m'] / row['d_fg3a'])}
        }
    },
    'cont': {
        'description': 'Defensive Shot Contests',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'hustle',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.contests',), 'fn': lambda row, ctx: row['contests']},
            'team': {'fields': ('s.contests',), 'fn': lambda row, ctx: row['contests']},
            'all_teams': {'fields': ('s.contests',), 'fn': lambda row, ctx: row['contests']}
        }
    },
    'blk': {
        'description': 'Blocks',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.blocks',), 'fn': lambda row, ctx: row['blocks']},
            'team': {'fields': ('s.blocks',), 'fn': lambda row, ctx: row['blocks']},
            'all_teams': {'fields': ('s.blocks',), 'fn': lambda row, ctx: row['blocks']}
        }
    },
    'defl': {
        'description': 'Deflections of the ball on Defense',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'hustle',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.deflections',), 'fn': lambda row, ctx: row['deflections']},
            'team': {'fields': ('s.deflections',), 'fn': lambda row, ctx: row['deflections']},
            'all_teams': {'fields': ('s.deflections',), 'fn': lambda row, ctx: row['deflections']}
        }
    },
    'stl': {
        'description': 'Steals',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.steals',), 'fn': lambda row, ctx: row['steals']},
            'team': {'fields': ('s.steals',), 'fn': lambda row, ctx: row['steals']},
            'all_teams': {'fields': ('s.steals',), 'fn': lambda row, ctx: row['steals']}
        }
    },
    'st+c': {
        'description': 'Steals + Charges Drawn',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.steals', 's.charges_drawn'), 'fn': lambda row, ctx: row['steals'] + row['charges_drawn']},
            'team': {'fields': ('s.steals', 's.charges_drawn'), 'fn': lambda row, ctx: row['steals'] + row['charges_drawn']},
            'all_teams': {'fields': ('s.steals', 's.charges_drawn'), 'fn': lambda row, ctx: row['steals'] + row['charges_drawn']}
        }
    },
    'fls': {
        'description': 'Personal Fouls',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': 'base',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.fouls',), 'fn': lambda row, ctx: row['fouls']},
            'team': {'fields': ('s.fouls',), 'fn': lambda row, ctx: row['fouls']},
            'all_teams': {'fields': ('s.fouls',), 'fn': lambda row, ctx: row['fouls']},
            'opponents': {'fields': ('s.opp_fouls',), 'fn': lambda row, ctx: row['opp_fouls']}
        }
    },
    'win%': {
        'description': 'Win percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'sheets': ['all_teams', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.wins', 's.games'), 'fn': lambda row, ctx: row['wins'] / row['games']},
            'team': {'fields': ('s.wins', 's.games'), 'fn': lambda row, ctx: row['wins'] / row['games']},
            'all_teams': {'fields': ('s.wins', 's.games'), 'fn': lambda row, ctx: row['wins'] / row['games']}
        }
    },
    'ortg': {
        'description': 'Team Offensive Rating When On Court',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.o_rtg_x10',), 'fn': lambda row, ctx: row['o_rtg_x10'] / 10},
            'team': {'fields': ('s.o_rtg_x10',), 'fn': lambda row, ctx: row['o_rtg_x10'] / 10},
            'all_teams': {'fields': ('s.o_rtg_x10',), 'fn': lambda row, ctx: row['o_rtg_x10'] / 10}
        }
    },
    'drtg': {
        'description': 'Team Defensive Rating When On Court',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA', 'ncaa'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.d_rtg_x10',), 'fn': lambda row, ctx: row['d_rtg_x10'] / 10},
            'team': {'fields': ('s.d_rtg_x10',), 'fn': lambda row, ctx: row['d_rtg_x10'] / 10},
            'all_teams': {'fields': ('s.d_rtg_x10',), 'fn': lambda row, ctx: row['d_rtg_x10'] / 10}
        }
    },
    'nooo': {
        'description': 'Net Offensive On/Off Team Rating',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'sheets': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.o_rtg_x10', 's.off_o_rtg_x10'), 'fn': lambda row, ctx: (row['o_rtg_x10'] / 10) - (row['off_o_rtg_x10'] / 10)}
        }
    },
    'ndoo': {
        'description': 'Net Defensive on/off Team Rating',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'sheets': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': None,
        'rate_domain': None,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('s.d_rtg_x10', 's.off_d_rtg_x10'), 'fn': lambda row, ctx: (row['d_rtg_x10'] / 10) - (row['off_d_rtg_x10'] / 10)}
        }
    },
    'ID': {
        'description': 'Shoot the Sheet Entity ID',
        'sections': ['identity'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': None,
        'rate_domain': None,
        'format': 'text',
        'decimal_places': 0,
        'width_class': 'auto',
        'link': None,
        'leagues': ['NBA'],
        'team_row_display': None,
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': {'fields': ('p.sts_id',), 'fn': lambda row, ctx: row['sts_id']},
            'team': {'fields': ('t.sts_id',), 'fn': lambda row, ctx: row['sts_id']},
            'all_teams': {'fields': ('t.sts_id',), 'fn': lambda row, ctx: row['sts_id']}
        }
    }
}